### ISSUE TITLE
Does not accept Follow requests from Mastodon

### ISSUE THREAD

**Issue by kaniini** [writeas/writefreely#11]
Mastodon does not address `Follow` activities.  While this is unfortunate, we must work around it.

**Comment by thebaer** [comment]
Hmm, I'm able to follow blogs from Mastodon. Do you have any more information about what's going on?

**Comment by thebaer** [comment]
Anymore information about this @kaniini? Otherwise I'll close it for now.

**Comment by jbfriedrich** [comment]
I am not sure what happens, but I have the same behaviour. I went to Mastodon and followed blog@thoughts.jason.re but I do not see any posts on Mastodon, nor do I see the instance in "following".

When I try to follow again, I get the option to "Cancel follow request", which indicates to me that Mastodon sent a "follow request" to WriteFreely, but the request is never answered or acknowledged.

<img width="895" alt="Screen Shot 2020-04-26 at 22 08 01" src="https://user-images.githubusercontent.com/1968991/80318434-6728d080-880a-11ea-9d2a-33c6ae0268eb.png">

**Comment by thebaer** [comment]
@jbfriedrich Usually this behavior happens when Mastodon doesn't respect the `Accept` response WriteFreely sends in reply to a `Follow` request. This can often happen if the `host` configuration value doesn't match your domain exactly -- in your case it should be: `host = https://thoughts.jason.re`

There might also be something funky with HTTP vs. HTTPS on Mastodon, since I noticed your site doesn't automatically redirect to HTTPS. Mastodon might've cached your **HTTP** address, depending on how you first looked up your blog. Unfortunately if that's the case, you'll need to delete the blog account in your Mastodon instance's database to fix it.

**Comment by jbfriedrich** [comment]
> @jbfriedrich Usually this behavior happens when Mastodon doesn't respect the `Accept` response WriteFreely sends in reply to a `Follow` request. This can often happen if the `host` configuration value doesn't match your domain exactly -- in your case it should be: `host = https://thoughts.jason.re`

Hey @thebaer, thanks for the quick reply. The host entry in the config is correct, in my case it is `host               = https://thoughts.jason.re`.

> There might also be something funky with HTTP vs. HTTPS on Mastodon, since I noticed your site doesn't automatically redirect to HTTPS.

That is weird, every browser I have, even in private or anonymous mode goes to https:// even though I type in http:// excplicitly 🤔. I will double check the træfik configuration.

> Mastodon might've cached your **HTTP** address, depending on how you first looked up your blog. Unfortunately if that's the case, you'll need to delete the blog account in your Mastodon instance's database to fix it.

It is not my Mastodon instance, I have an account on https://mastodon.social. I did not specify a protocol at all, I searched for **@blog@thoughts.jason.re** within the Mastodon Web Interface.

Any advise how to debug this further?

**Comment by thebaer** [comment]
The quickest way would be to get into the logs on a Mastodon instance and see how it's responding to that `Accept` activity sent out by WF. Especially with debug logs turned on, that should indicate why it's not taking the `Accept`.

Otherwise, if you run WF with the `--debug` flag, I believe this will work:

* Send another follow request from Mastodon
* Watch your logs
  * You should see the `Follow` request come in, and then the `Accept` request go out
  * At the end, you should see `Status` and `Response` lines -- those might give some more information

**Comment by jbfriedrich** [comment]
> The quickest way would be to get into the logs on a Mastodon instance and see how it's responding to that `Accept` activity sent out by WF. Especially with debug logs turned on, that should indicate why it's not taking the `Accept`.

That should be the quickest way, I guess. Not sure how quickly – and if at all – I can get one of the Mastodon admins to do that 😄. 

> Otherwise, if you run WF with the `--debug` flag, I believe this will work:
> 
> * Send another follow request from Mastodon
> * Watch your logs
>   
>   * You should see the `Follow` request come in, and then the `Accept` request go out
>   * At the end, you should see `Status` and `Response` lines -- those might give some more information

Thanks, I will try that later tonight and report back. Having this documented here might help people later who encounter the same problem 👍 .

**Comment by jbfriedrich** [comment]
Now I was able to invest some more time and properly debug my issue. It seems that I forgot to install openssl: 
```
microblog_app.1.ok11fuahsorq@docker-host    | 2020/05/02 04:14:31 "GET /.well-known/webfinger?resource=acct:blog@thoughts.jason.re" 200 1.889587ms "http.rb/4.3.0 (Mastodon/3.1.3; +https://mastodon.social/)"
microblog_app.1.ok11fuahsorq@docker-host    | 2020/05/02 04:14:31 Unable to generate private key: exec: "openssl": executable file not found in $PATH
microblog_app.1.ok11fuahsorq@docker-host    | ERROR: 2020/05/02 04:14:31 database.go:2302: Unable to INSERT new activitypub keypair: Error 1048: Column 'public_key' cannot be null
microblog_app.1.ok11fuahsorq@docker-host    | 2020/05/02 04:14:31 "GET /api/collections/blog" 200 26.844795ms "http.rb/4.3.0 (Mastodon/3.1.3; +https://mastodon.social/)"
microblog_app.1.ok11fuahsorq@docker-host    | 2020/05/02 04:14:31 Unable to generate private key: exec: "openssl": executable file not found in $PATH
microblog_app.1.ok11fuahsorq@docker-host    | ERROR: 2020/05/02 04:14:31 database.go:2302: Unable to INSERT new activitypub keypair: Error 1048: Column 'public_key' cannot be null
microblog_app.1.ok11fuahsorq@docker-host    | 2020/05/02 04:14:31 "GET /api/collections/blog" 200 2.436516ms "http.rb/4.3.0 (Mastodon/3.1.3; +https://mastodon.social/)"
microblog_app.1.ok11fuahsorq@docker-host    | 2020/05/02 04:14:31 "GET /api/collections/blog/outbox" 200 2.221191ms "http.rb/4.3.0 (Mastodon/3.1.3; +https://mastodon.social/)"
microblog_app.1.ok11fuahsorq@docker-host    | 2020/05/02 04:14:31 "GET /api/collections/blog/following" 200 1.370245ms "http.rb/4.3.0 (Mastodon/3.1.3; +https://mastodon.social/)"
microblog_app.1.ok11fuahsorq@docker-host    | 2020/05/02 04:14:31 "GET /api/collections/blog/followers" 200 1.905615ms "http.rb/4.3.0 (Mastodon/3.1.3; +https://mastodon.social/)"
```
I built a Docker container for writefreely, so it is as minimal as possible. After installing the `openssl` binary, I was able to be followed by my mastodon.social account, and every new post is now displayed properly in the federated timeline.

**Comment by kode54** [comment]
I get something completely different.

```
2022/02/11 08:57:16 Follow: {"@context":["https://www.w3.org/ns/activitystreams"],"actor":"https://vulpine.club/users/kode54","id":"https://vulpine.club/50a37899-bc54-4da1-9fd5-aaf52d7b0f7d","object":"https://blog.kode54.net/api/collections/chris","type":"Follow"}
2022/02/11 08:57:16 Fetching actor https://vulpine.club/users/kode54 locally
2022/02/11 08:57:16 "POST /api/collections/chris/inbox" 200 4.917896ms "http.rb/5.0.4 (Mastodon/3.4.6+glitchfox-prod2022020301; +https://vulpine.club/)"
2022/02/11 08:57:18 POST
ERROR: 2022/02/11 08:57:18 activitypub.go:538: Can't dump: unsupported protocol scheme ""
ERROR: 2022/02/11 08:57:18 activitypub.go:438: Unable to make activity POST: Post "": unsupported protocol scheme ""
```
