### ISSUE TITLE
Pubgate: unsupported protocol scheme

### ISSUE THREAD

**Issue by robjloranger** [writeas/writefreely#116]
### Describe the bug

Confirming the fix in #111, we discovered a different issue with followers using pubgate.

All POST requests against the Pubgate user return an error:
```console
..Post : unsupported protocol scheme ""
```

It looks like we store an empty string as their inbox.

### Steps to reproduce (if necessary)
1. Follow a writefreely (running the fix for #111) blog from pubgate
2. Post or delete a post on the writefreely blog
3. Check logs

### Expected behavior
POSTs should go out to an actual URL and succeed.

### Application configuration
 - **Single mode** 
 - **Database?** mysql?
 - **Open registration?** no
 - **Federation enabled?** yes

**Version or last commit**:
WF commit 95215aa on branch gh100

**Comment by thebaer** [comment]
Good catch. To be sure, this is the error returned on our end? If so, what's the full log around that error look like?

**Comment by robjloranger** [comment]
```console
Jun 03 15:32:53 mangrove rob[8586]: 2019/06/03 15:32:53 POST
Jun 03 15:32:53 mangrove rob[8586]: ERROR: 2019/06/03 15:32:53 log.go:26: Couldn't delete post! Post : unsupported protocol scheme ""
```

**Comment by thebaer** [comment]
I see. So looking into the code... actually we're not storing the user's _shared_ inbox (I assume it doesn't have one). Looking at the database, we do have an _inbox_ for that pubgate user.

So to fix this issue, we need to fix the logic in various `activitypub.go` funcs that compile an `inboxes` map to fall back to a `RemoteUser`s `Inbox` if their `SharedInbox` is empty. E.g. in places like this: https://github.com/writeas/writefreely/blob/95215aa39db51f9510ded34480a62fb61242c4dd/activitypub.go#L550-L557

**Comment by robjloranger** [comment]
perfect, thanks @thebaer

**Comment by thebaer** [comment]
No problemo! If you want to tackle this fix, please feel free to assign yourself.

**Comment by robjloranger** [comment]
just testing now
