### ISSUE TITLE
Asset sqlite.sql can't read by error: Error reading asset sqlite.sql

### ISSUE THREAD

**Issue by tlattimore** [writeas/writefreely#118]
### Describe the bug
I am receiving the following bug on when running `./writefreely --config` on MacOS 10.14.4. 

```
ERROR: 2019/06/06 16:20:42 log.go:26: Unable to load schema file: Asset sqlite.sql can't read by error: Error reading asset sqlite.sql at /home/mattbaer/projects/go/src/github.com/writeas/writefreely/sqlite.sql: open /home/mattbaer/projects/go/src/github.com/writeas/writefreely/sqlite.sql: no such file or directory
```

### Steps to reproduce (if necessary)
- Run `./writefreely --config` with the following settings:
```➞ ./writefreely --config
Loaded configuration config.ini.

  ✍ WriteFreely Configuration ✍

  This quick configuration process will update the application's config
file, config.ini.

  It validates your input along the way, so you can be sure any future
errors aren't caused by a bad configuration. If you'd rather configure your
server manually, instead run: writefreely --create-config and edit that
file.

 Server setup
Development
Local port: 8080

 Database setup
SQLite
Filename: test.sql

 App setup
Single user blog
Admin username: admin
Admin password: admin
Blog name: testier
Public URL: http://localhost:8080
Disabled
```
### Expected behavior
What should've happened?
- The application setup with the necessary configuration and not thrown an error

### Application configuration
 - **Single mode or Multi-user mode?** Single 
 - **Database?** [sqlite]
 - **Open registration?** [no]
 - **Federation enabled?** [no]

**Version or last commit**:
- v0.9.1

**Comment by tlattimore** [comment]
It looks like downgrading to `v0.9.0` resolves this issue.

**Comment by robjloranger** [comment]
Looks like a hard coded file path.

**Comment by thebaer** [comment]
WF looks for assets in the file system when `go-bindata` is run with the `-debug` flag. Otherwise the assets get compiled into the executable, which is why we leave that flag off for release builds. But I think the v0.9.1 macOS build got messed up somehow (by including the `-debug` flag). A few other developers had similar issues with the Windows build -- both of them must've gotten botched.

**Comment by thebaer** [comment]
@tlattimore I just rebuilt v0.9.1 and uploaded the new macOS version. When you have a chance, could you try configuring again with that build and let us know if it's fixed? (I don't have a Mac to test on right now.)

**Comment by tlattimore** [comment]
Thanks, @thebaer. The build for `v0.9.1` is now working as expected.

**Comment by thebaer** [comment]
Awesome, thanks for letting me know. Just uploaded the fixed Windows build, as well.
