### ISSUE TITLE
Commenting

### ISSUE THREAD

**Issue by drequivalent** [writeas/writefreely#12]
Suggesting a thing that's pretty standard around the Fediverse: show replies to an article as a comment section.

Also, add an option to enable/disable them, globally or on a singular article.

**Comment by thebaer** [comment]
Thanks for the suggestion! Could you share this [on the forum](https://discuss.write.as/c/feedback/feature-requests), instead? Then I can respond over there. We're keeping the issue tracker [limited to bug reports](https://github.com/writeas/writefreely/blob/master/CONTRIBUTING.md#contributing-to-writefreely) for now.
