### ISSUE TITLE
Failed to post, 401 not logged in

### ISSUE THREAD

**Issue by rushsteve1** [writeas/writefreely#140]
### Describe the bug
After writing a post when you go to save the draft or post it publicly an alert comes up saying `Failed to post. Please try again.`

The `POST` request to /api/posts responds with a 401 code and the response is:
```
{"code":401,"error_msg":"Not logged in."}
```

### Steps to reproduce (if necessary)
1. Write post
2. Click on save to drafts
3. Alert comes up, `POST` request fails.

### Expected behavior
The draft should have saved or posted.

### Application configuration
 - **Single-user mode**
 - **Database?** mysql
 - **Open registration?** No
 - **Federation enabled?** Yes

**Version or last commit**: writefreely v0.10.0

Original issue https://github.com/YunoHost-Apps/writefreely_ynh/issues/62

**Comment by thebaer** [comment]
Thanks for the report. A few questions:

* Are you publishing via the web application or directly to the API via another client?
* If web, what is the URL path you're publishing from? (that is, the part that comes after the domain name, e.g. `/`)
* Can you share your server logs around this?  
* Just to be sure, are you logged in? Does publishing to your blog instead of a draft work?

**Comment by rushsteve1** [comment]
- Via the web application
- `/me/new`
- No? (see below)
- I can access all other login-restricted pages and they work fine, so seemingly yes.

Something very odd just happened. I went to reproduce the bug which had happened repeatedly up until now, even after a complete re-install, so that I could get the logs. So I don't have the logs for when it was failing.

And the bug didn't happen, the post succeeded.

I changed nothing, so I have no idea what changed that allowed me to post.

**Comment by thebaer** [comment]
Hmm, very odd. Well let us know if you notice it again, and be sure to include the server logs then. I wasn't able to replicate on my own single-user instance (though it's not a yunohost build), so I'll close this for now.

**Comment by Ry3yr** [comment]
I'd like to request a reopening of the issue.

Trying to edit a post
(In this case add the line
* <a target="_blank" href="https://www.youtube.com/@fruzi/videos#https://m.youtube.com/watch?v=drBC4ZrM1zA">fruz</a><br> 
to the post https://paper.wf/alcea/audio-ripper-list)

Will throw the error message in question.

This instance (paper wf) is not hosted by me .

Error in question:
https://i.ibb.co/T2nnQm1/Screenshot-20230713-181615-Opera.png
