### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by Fastidious** [writeas/writefreely#146]
### Describe the bug
`Writefreely` will fail to run. It shows:
```
2019/07/23 14:41:45 Serving on http://quark.rocks:8080
2019/07/23 14:41:45 ---
ERROR: 2019/07/23 14:41:45 app.go:402: Unable to start: listen tcp 13.82.172.61:8080: bind: cannot assign requested address
```
### Steps to reproduce (if necessary)
I tried running `writefreely`. Will not run.

### Expected behavior
I would expect it to run.

### Application configuration
 - **Single mode or Multi-user mode?** Single mode
 - **Database?** [mysql/sqlite] sqlite
 - **Open registration?** [yes/no] No
 - **Federation enabled?** [yes/no] No

**Version or last commit**: `WriteFreely 0.10.0`

### Additional information
My VPS (Azure VM) has only a private IP bound on the interface, although it is exposed with a public IP to the world.

**Comment by Fastidious** [comment]
Had to change the FQDN for `localhost`, and that worked.

**Comment by thebaer** [comment]
Hey, this is just a misconfiguration. It looks like the `bind` value in the `[server]` section of your config is set to `quark.rocks`, and the application rightfully can't bind to its address.

For most setups, you'll want to bind to `localhost`, i.e. if you leave `bind` blank and it should work. Let us know if that doesn't, though.
