### ISSUE TITLE
No login button

### ISSUE THREAD

**Issue by MasterGroosha** [writeas/writefreely#15]
On the main page, there's no login button. It took me a while to think about manually adding `/login` to URL and proceeding to auth page.

Maybe there's something wrong on my side, since I'm also having [issues](https://github.com/writeas/writefreely/issues/7#issuecomment-438038163) with installation.

**Comment by thebaer** [comment]
Is your blog is configured for a single user? Or multiple?

**Comment by MasterGroosha** [comment]
Single user, but federated.

**Comment by thebaer** [comment]
Thanks, fixing now.

**Comment by Fastidious** [comment]
The always showing menu breaks it for mobile, FYI. Perhaps the whole mobile view needs some work?
