### ISSUE TITLE
When Alice (a fediverse actor) tries to follow a writefreely actor (Bob) and Alice already follows Bob then writefreely crashes.

### ISSUE THREAD

**Issue by qwazix** [writeas/writefreely#159]
### Describe the bug
When a follow is already registered in the writefreely database, repeating the follow request crashes writefreely

### Steps to reproduce (if necessary)
1. Follow a writefreely author from an instance you control
2. Fool your instance to think step 1 never happened (remove the follow from the database)
3. Repeat 1
4. Observe writefreely crash

### Expected behavior
Nothing probably. Or maybe refresh the public key with the new one?

### Application configuration
 - **Single mode** 
 - **sqlite** [mysql/sqlite]
 - **Open registration?** no
 - **Federation enabled?** yes

**Version or last commit**: 0.10.0

[log of installation, execution and crash with --debug](https://github.com/writeas/writefreely/files/3480381/writefreely.log)

**Comment by robjloranger** [comment]
So far I think I figured out the panic, there is an error check when inserting the new actor into the remote users table which previously only checked if the error was **NOT** for a duplicate key. So if there was a duplicate key it would just continue on trying to proceed, however the response from the db transaction is nil when there is an error, hence the panic.

I changed the check to check for _any_ error and can now POST duplicate follow requests, only seeing an error logged that the key was not unique.

I will submit a PR and we can go from there.
