### ISSUE TITLE
Accepts of follows are on the wrong origin

### ISSUE THREAD

**Issue by puckipedia** [writeas/writefreely#16]
from what i can tell:
https://github.com/writeas/writefreely/blob/c996ae1cadbc48974094b656884dc09ca93d30d5/activitypub.go#L262
this seems to e.g. generate `https://puckipedia.com/1234-5678-accept` from a follow of id `https://puckipedia.com/1234-5678`, which should not be accepted by any software ever. (i'm looking at you, yes you). If this is correct, this seems to be a violation of the spec (in that "every object should be resolvable", which i don't really care about for more transient objects like accepts), as i could've already put an object at this location. As such, Kroeg wisely rejects the Accept.

**Comment by thebaer** [comment]
Yeah, I was looking at URLs from a certain federated platform when implementing this, which was not right. Thanks for reporting!

**Comment by puckipedia** [comment]
wwait, so if I feed in `https://example.com/follow`, what ID does it send the accept as?

**Comment by thebaer** [comment]
It should come back as `https://example.com/follow#accept` with the latest commit

**Comment by puckipedia** [comment]
the issue is that you don't own `example.com`, so why would you be allowed to say that you own an object on that domain?

**Comment by thebaer** [comment]
I'm following Plume's lead here, which did exactly this when last I checked. I haven't looked at other platforms yet to figure out what a better ID would be -- but I'm open to suggestions!

**Comment by puckipedia** [comment]
generate a random GUID and do something like `https://contoso.com/activities/12345678-1234-1234-12345678`, as long as it's on the same origin; it's mostly transient after all

**Comment by thebaer** [comment]
Gotcha. And that should actually resolve to the `Accept` activity? Do you know how long it has to be retained?

**Comment by puckipedia** [comment]
"officially" it has to, but seeing as noone will ever refer back to it (you're not going to `Announce` it, etc), it definitely doesn't have to resolve (it doesn't on Mastodon, for example).

Mastodon actually uses `https://example.com/users/{username}#accepts/follows/{internal follow ID}`, for reference, which doesn't resolve either

**Comment by thebaer** [comment]
Okay cool. I'll get this fix in the next version.
