### ISSUE TITLE
Tar is bombing the cwd with files

### ISSUE THREAD

**Issue by qwazix** [writeas/writefreely#160]
### Describe the bug
Untarring the writefreely release with the customary `tar xzvf writefreely_x.x.x_os_arch.tar.gz` explodes littering the current directory with files. The tar should have a root directory so that untarring creates only one directory in the cwd.

### Steps to reproduce (if necessary)
1. Download writefreely
2. `tar xzvf writefreely_x.x.x_os_arch.tar.gz` 
3. The contents litter the current directory

### Expected behavior
A single directory named `writefreely` should be extracted with the rest of the files placed inside it

**Version or last commit**: 0.10.0

**Comment by thebaer** [comment]
Thanks, this should be a quick fix. Just need to add the dir in `make release`.

**Comment by robjloranger** [comment]
I will update the one click image scripts after

**Comment by thebaer** [comment]
Yep, though this fix will go out with v0.11 -- so we should be sure not to include the change in the v0.10 image we're going to release.

If either of you want to tackle this fix, feel free to assign yourself the issue here and open a PR.
