### ISSUE TITLE
Error resolving follow ID

### ISSUE THREAD

**Issue by robjloranger** [writeas/writefreely#167]
### Describe the bug

When debugging #159, I noticed an error in the logs during a follow request.
`ERROR: 2019/08/08 10:16:55 activitypub.go:278: Didn't resolve follow ID`

### Steps to reproduce (if necessary)

1. Watch the logs on an instance you control
2. follow a user on that instance from elsewhere
3. see error in the logs

### Expected behavior

never any errors? :grin: 

### Application configuration

 - **Single mode or Multi-user mode?** multi
 - **Database?** sqlite
 - **Open registration?** yes
 - **Federation enabled?** yes

**Version or last commit**:

latest develop: 8557119

**Comment by thebaer** [comment]
Do you know the ID of the actor you were unable to follow? I think that'd be the first step to deciding whether or not this is a bug we should fix.

**Comment by robjloranger** [comment]
Not off hand, I do remember that I was able to follow them. But the error was present all the same. I can grab some more info and get back to you.

**Comment by thebaer** [comment]
I'd imagine this was an error on the follower's part, rather than ours. So I'm going to close this for now, and we'll reopen if there appears to be an issue on our end.
