### ISSUE TITLE
v0.10.0 release binaries for linux ships without MathJax 

### ISSUE THREAD

**Issue by RJ722** [writeas/writefreely#176]
### Describe the bug

The [linux release binary v0.10.0][bin] ships with an empty MathJax directory. Therefore, no math is rendered on a blog despite turning on MathJax.

This issues was originally reported on [discourse](https://discuss.write.as/t/new-formatting-syntaxes/43/15?u=rj722).

[bin]: https://github.com/writeas/writefreely/releases/download/v0.10.0/writefreely_0.10.0_linux_amd64.tar.gz

### Steps to reproduce (if necessary)
1. Untar [linux release binary v0.10.0][bin]
2. the `static/js/mathjax` directory is empty.

### Application configuration
 - **Single mode or Multi-user mode?** Multi-user mode
 - **Database?** mysql
 - **Open registration?** no
 - **Federation enabled?** yes

**Version or last commit**:

v0.10.0

**Comment by robjloranger** [comment]
Thanks for this @RJ722, looks like our update script needs to account for using a submodule for MathJax. Sorry for the inconvenience.

**Comment by robjloranger** [comment]
Hey sorry for the delay here, I will work on this change today.

**Comment by thebaer** [comment]
I've updated the [v0.10 builds](https://github.com/writeas/writefreely/releases/tag/v0.10.0) to all include Mathjax, so this particular issue is resolved now.

We'll continue work on optimizing this on #181.
