### ISSUE TITLE
Retrieve a Collection API endpoint uses request content-type instead of accept header

### ISSUE THREAD

**Issue by carbontwelve** [writeas/writefreely#178]
### Describe the bug
When using the Retrieve a Collection API endpoint as [documented here](https://developers.write.as/docs/api/#retrieve-a-collection) I notice that when sending a request with the `Accept` header correctly set to `application/json` the server was incorrectly returning `Content-Type`:`text/html`.

Upon looking at the source code I can see this bug is seemingly due to the following line: https://github.com/writeas/writefreely/blob/master/collections.go#L321

### Steps to reproduce (if necessary)
1. Request the GET `/api/collections/{COLLECTION_ALIAS}` API endpoint with `Accept` header set for `application/json`
2. Server responds with HTML.

### Expected behavior
The request is stating it accepts json the server should respond with content type json or HTTP 415 Unsupported Media Type if not supported. Given that the API supports returning JSON it should have responded with JSON.

The following line https://github.com/writeas/writefreely/blob/master/collections.go#L321 potentially needs amending to include the Accept header as well.

**Comment by thebaer** [comment]
Thanks for the report!

For a first pass, we can refactor `IsJSON()` to accept a `http.Request` instead of a `string` and check both the `Content-Type` and `Accept` headers.

@robjloranger want to take a look?

**Comment by robjloranger** [comment]
:+1:
