### ISSUE TITLE
Getting mysqld error on schema import

### ISSUE THREAD

**Issue by Fastidious** [writeas/writefreely#18]
### Describe the bug

Getting:
```
ERROR 1067 (42000) at line 99: Invalid default value for 'updated'
```
When running:
```
mysql -u USERNAME -p writefreely < schema.sql
```
Running mysqld 5.7.24 on Ubuntu 18.04.1.

**Version or last commit**:
v0.2

Evidently [this commit](https://github.com/writeas/writefreely/commit/3bf10d8074f00997f9c86c3bcade778f449fcbe7) isn't fixing it for me, nor this [workaround](https://github.com/writeas/writefreely/commit/3bf10d8074f00997f9c86c3bcade778f449fcbe7#commitcomment-31252910).

**Comment by Fastidious** [comment]
Adding:
```
SET sql_mode = '';
```
to the top of `schema.sql` fixed my problem. See this [answer](https://stackoverflow.com/a/37696251).

**Comment by thebaer** [comment]
Without changing your config, could you try importing the latest `schema.sql` now?

**Comment by Fastidious** [comment]
Let me try.

**Comment by Fastidious** [comment]
@thebaer it worked.

**Comment by thebaer** [comment]
Excellent :+1:
