### ISSUE TITLE
Wrong URL for write.css

### ISSUE THREAD

**Issue by Fastidious** [writeas/writefreely#19]
Fresh install, no proxying it yet. I am accessing it at http://myhostname.domain.com:8080. All assets are loading fine, but `write.css` which tries to load from http://localhost:8080/css/write.css instead.

**Comment by thebaer** [comment]
What's your configured `host` value?

**Comment by Fastidious** [comment]
@thebaer it is `http://localhost:8080`. Everything else loads (fonts, js, etc.) fine, but `write.css`.

**Comment by Fastidious** [comment]
@thebaer what should the `host` value be? This is going to be proxied through a web server, no?

**Comment by thebaer** [comment]
Ah, there are probably still some places that include the full URL for the CSS. We might keep that, especially for the eventual support of path installation. But either way, your `host` value should be the full public URL you're accessing your install on, so for you: `http://myhostname.domain.com:8080`

**Comment by thebaer** [comment]
I'll add some documentation around configuring the application soon.

**Comment by Fastidious** [comment]
@thebaer so, right now I will need to change it, and when I setup my web server for proxying it, I will have to change it again, correct?

**Comment by thebaer** [comment]
That's correct
