### ISSUE TITLE
Unexpected markdown rendering: newlines

### ISSUE THREAD

**Issue by cerisara** [writeas/writefreely#193]
When writing a post, I assume I'm writing in some flavor or markdown.
But then, it's pretty surprising to see that every newline that I insert in my blog
is rendered as a newline: I'd expect in markdown paragraphs to be separated by an empty line,
and not by a newline.

The  expected rendered output, in order to better comply with standard markdown rendering, would be to join all the lines together into a single paragraph until an empty line is found.

Thanks for the great software !

**Comment by robjloranger** [comment]
Hi @cerisara, thanks for the issue report. :smiley: 

Can you show an example of a post that is not behaving as expected?

Also can you define a newline and an empty line, so I know the HTML you are expecting?

I tried a small test and found the following:
- a sentence broken by a single new line remains part of the same logical paragraph, but that newline is preserved. (same as github flavor but they use a line break)
- a sentence broken by a double space and then a new line inserts a line break, still the same logical paragraph.
- a sentence broken by an empty line create two separate paragraphs.

Behind the scenes we are using [github.com/russross](https://github.com/russross/blackfriday), as far as I can tell we are not changing any default line/new line behaviour. @thebaer may know more about that.

All that said, I'm eager to get this all sorted out for you.

**Comment by thebaer** [comment]
Thanks for the input @cerisara!

This is indeed an [ongoing discussion](https://discuss.write.as/t/markdown-inconsistencies-and-markdown-flavour/750) we've been having. But the choice for honoring newlines exactly as they're typed was a deliberate design decision, to make the platform usable for such writing as poetry. (As such, I'll close this issue -- but feel free to continue discussing.)

Still, we'd like to potentially support different Markdown flavors, configured at the instance-level. If you have any thoughts on a standard we should use, we'd love to hear about it.

**Comment by cerisara** [comment]
Thank you both of you for your reply !
OK, I understand the design decision, especially with regard to writing poetry: it's definitely better for this use case. It's probably not as good for another use case: when people are syncing their blog with a git server (in addition to publishing them on writefreely), because long lines are bad for git. They might also be not so nice to navigate in in post-edition.
But it's clear that there's a compromise to find for the default behaviour: then, it'd be great to indeed have the choice, at the instance or blog level ! :-)
Thanks again.
