### ISSUE TITLE
Add a way to hide the menu when not logged in

### ISSUE THREAD

**Issue by vvug** [writeas/writefreely#199]
Hi! WriteFreely is super nice and clean, however I'd like the Menu to be hidden when I'm not logged in, so the people visiting my blog won't see it. I don't mind manualy adding `/login` to the URL when I need to log in. Is this possible? Thanks!

**Comment by thebaer** [comment]
Hi! Yep, this is possible with a little custom CSS. I've explained how to do that over [on our forum](https://discuss.write.as/t/add-a-way-to-hide-the-menu-when-not-logged-in/894), as we only use GitHub for bug reports.
