### ISSUE TITLE
Question: Any reason why this would not work with PostgreSQL?

### ISSUE THREAD

**Issue by carbontwelve** [writeas/writefreely#20]
The server I am planning on using this on only has PostgreSQL installed, just wondered if there was anything in the queries being used that would be incompatible with that database? I haven't tried it yet, but  I seem to remember PostgreSQL being a good drop in replacement for MySQL.

**Comment by andreapavoni** [comment]
+1 here

after a very quick look at the source code, it uses MySQL. I'd like to use it with PG too.

**Comment by carbontwelve** [comment]
@andreapavoni they both understand SQL, so theoretically I should be able to have it connect to PostgreSQL and the queries work. I don't have time tonight otherwise I would test.

**Comment by carbontwelve** [comment]
Looks like everything database related is centralised into `database.go` so worst case would be to make that able to interoperate with MySQL, PostgreSQL and possibly SQLite (the later I know was an opened issue recently, with a fork made.)

**Comment by andreapavoni** [comment]
I'm not a Go expert (I wrote something with it several years ago), but I've seen elsewhere that is possible to support several SQL databases by just importing the right drivers all at once and adding some glue code to select the right one.

**Comment by BenOvermyer** [comment]
SQLite support is coming. Support for PostgreSQL shouldn't be any harder.

**Comment by thebaer** [comment]
Since this isn't a bug report, let's continue this discussion [on the forums](https://discuss.write.as/t/db-postgresql-support/184).
