### ISSUE TITLE
I can't publish an article

### ISSUE THREAD

**Issue by paradoxisme** [writeas/writefreely#200]
I have installed writefreely on yunohost and I never managed to publish an article

### Steps to reproduce (if necessary)
After installed write freely on yunohost
1. I connect to admin
2. I write "test" and I click to send
3. I have a popup with this message : Failed to post. Please try again

When I launch writefreely on debug mode, I have this message :
ERROR: 2019/10/29 19:48:02 auth.go:21: Couldn't parseHex on '': Invalid UUID string
2019/10/29 19:48:02 "POST /api/collections/admin/posts" 401 110.853µs "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"

### Expected behavior
A new article should be write

### Application configuration
 - **Multi-user mode?** 
 - **Database?** [mysql]
 - **Open registration?** [no]
 - **Federation enabled?** [yes]

**Version or last commit**:
0.10.0~ynh1

**Comment by thebaer** [comment]
Going to close for now, since we don't have enough information to determine whether or not this is a bug. Please feel free to send that along whenever you can, and we'll re-open this if necessary.

**Comment by hairylarry** [comment]
I am having this exact bug. If we can reopen this thread I will work with you on trying to resolve this. I have a writefreely blog on write.as I am wanting to move onto yunohost.

Thanks

**Comment by mathieunicolas** [comment]
Same here, just installed Writefreely on a Yunohost instance and I got the exact same bug as described.
PeerTube had this problem before, which happens when there is a Yunohost session opened in the same browser. I'm not techy enough to understand the why, but I just tested and if the Yunohost session is closed, there is no problem.

**Comment by JiriKrecek** [comment]
it seams like auth.go cant handle if the browser sends Authorization header, so when you have basic auth on proxy, you cant publish
auth.go:21: Couldn't parseHex on '': uuid: incorrect UUID length 30 in string "Basic amlya2E6MTJLcmVjZWszNA=="
