### ISSUE TITLE
Admin blog articles cannot be viewed publicly

### ISSUE THREAD

**Issue by VonKavalier** [writeas/writefreely#201]
### Describe the bug
I created a blog as the admin user and changed the configuration to make it public.

I wrote an article and published it, but I cannot see it unless I write the complete url of it. It doesn't appear on the /read/ and appears on the blog page only if I'm logged in.

But I do see it public when I check the configs of the blog in the admin panel.

### Expected behavior
I should see it without being logged in in the /read/ page and the blog page.

### Application configuration
 - **Multi-user** 
 - **Database?** [mysql]
 - **Open registration?** [yes]
 - **Federation enabled?** [yes]

**Version or last commit**:
    v0.10.0

**Comment by thebaer** [comment]
Thanks for the report, @VonKavalier -- how did you resolve this?
