### ISSUE TITLE
Template error in version 0.11.0

### ISSUE THREAD

**Issue by Kansattica** [writeas/writefreely#207]
I just updated to WriteFreely 0.11.0 from 0.10.0. I downloaded the tarball from the releases page, extracted it into a new place, and copied over my database, keys, and config.ini. I ran the database migration and, when I start writefreely and try to load the home page, I get an error screen and the following message in the console.

```
ERROR: 2019/11/11 11:57:56 collections.go:820: Unable to render collection index: template: collection.tmpl:74:125: executing "collection" at <.Host>: can't evaluate field Host in type writefreely.PublicPost
ERROR: 2019/11/11 11:57:56 handle.go:508: [Web handler] 500: template: collection.tmpl:74:125: executing "collection" at <.Host>: can't evaluate field Host in type writefreely.PublicPost
```

I assume this is because your PublicPost struct doesn't have a .Host property, as seen [here](https://github.com/writeas/writefreely/blob/bca678aee5a50fbb29ffe923ec701be6aadabc27/posts.go).

**Comment by robjloranger** [comment]
Thanks for the report and sorry about the inconvenience. I will investigate now and get a fix up ASAP.

**Comment by robjloranger** [comment]
@Kansattica I'm having trouble reproducing this with `v0.11.0`, I will double check using the release tarball but in the meantime could you share your server config? not the database or anything that should be secret, just the options set in the [app] section of `config.ini`.

**Comment by robjloranger** [comment]
I can't reproduce with the `v0.11.0` tarball either, did you stop and restart your writefreely service ater the update?

**Comment by diazepan** [comment]
I confirm the bug. Here are the options in the app section

[app]
site_name         = Torta de Frambuesa
host              = https://blog.pueseso.club
theme             = write
disable_js        = false
webfonts          = true
single_user       = true
open_registration = false
min_username_len  = 3
max_blogs         = 1
federation        = true
public_stats      = true
private           = false

**Comment by thebaer** [comment]
Confirmed -- this happens if a blog has pinned posts. Fixing now and will issue a new release shortly.
