### ISSUE TITLE
Font configuration options

### ISSUE THREAD

**Issue by schu** [writeas/writefreely#211]
Is there a way to a) change the font throughout(!) writefreely and b) disable/remove all default fonts and related resources (webfont.js etc)?

For example, to change the font to Inter I added the following customization (via the web UI):

```
@import url('https://rsms.me/inter/inter.css');
html, body, textarea, pre, body#post article, body#collection article, body#subpage article, span, .font { font-family: 'Inter', sans-serif !important; }
@supports (font-variation-settings: normal) {
  html, body, textarea, pre, body#post article, body#collection article, body#subpage article, span, .font { font-family: 'Inter var', sans-serif !important; }
}
```

in combination with setting both  `disable_js = true` and `webfont = false` in my config. That works to some extent (public pages are mostly using Inter now), but writefreely still loads all its default fonts and the menu and admin area still using the default fonts as well.

It looks like templates and theming are pretty tied to the code and it's not possible without actually changing the code.

Am I missing something?

**Comment by thebaer** [comment]
Hey, thanks for bringing this up. I went ahead and [answered this on our forum](https://discuss.write.as/t/font-configuration-options/938/2), where we discuss things like this (we only use GitHub for bug reports). Let's continue the discussion over there, if you don't mind.
