### ISSUE TITLE
Deleting post does not delete on Fediverse

### ISSUE THREAD

**Issue by barbrastreisand** [writeas/writefreely#223]
### Describe the bug
I create a new blog recently and allowed federation. After following the blog from my own Pleroma instance, I went about testing the function of posting to the fediverse, which worked fine. When deleting the post from the WF instance, the posts still appear on the feed of the account in the Fediverse.

WF instance: blog.lexserv.xyz
Pleroma instance: social.lexserv.xyz
Pleroma user: alex

### Steps to reproduce (if necessary)
1. Make post
2. Check to see if post has appeared in fediverse
3. It has, so now delete post
4. Post still exists on fediverse

### Expected behavior
The post should be deleted.

### Application configuration
 - **Single mode or Multi-user mode?** Single
 - **Database?** [mysql/sqlite] SQLite
 - **Open registration?** [yes/no] No
 - **Federation enabled?** [yes/no] Yes

**Version or last commit**:
0.11.1

**Comment by thebaer** [comment]
Thanks for the report! Tested and verified this is happening with Pleroma, but not Mastodon. Not sure what we need to do on our end to fix this -- nothing in particular jumped out at me -- so I've opened [pleroma#1481](https://git.pleroma.social/pleroma/pleroma/issues/1481) to hopefully figure that out.
