### ISSUE TITLE
Dead link at https://write.privacytools.io/about

### ISSUE THREAD

**Issue by erm3nda** [writeas/writefreely#227]
Code of conduct link is dead: https://github.com/privacytoolsIO/privacytools.io/blob/master/CODE_OF_CONDUCT.md

I thought that in that era links get checked by automated processes. 

Regards.

**Comment by thebaer** [comment]
Hey, write.privacytools.io is actually an _instance_ of WriteFreely, and the About page is entirely customizable, so this isn't something for us to fix in the software itself.

I'd recommend reaching out to them (following the instructions on their About page) and letting them know the link is dead.

**Comment by erm3nda** [comment]
Lol, im sorry for my mistake :-) thank you.

**Comment by thebaer** [comment]
No worries! :smile:
