### ISSUE TITLE
Query: How different AGPL license is from MIT or Apache2.0?

### ISSUE THREAD

**Issue by makeitcount** [writeas/writefreely#229]
I'm curious to try it out but not sure about the license. Can someone help?

**Comment by thebaer** [comment]
You can see what the AGPL license involves at the top of the [LICENSE page](https://github.com/writeas/writefreely/blob/develop/LICENSE) itself. Otherwise, here's a nice site that summarizes different licenses too: https://choosealicense.com

**Comment by cauerego** [comment]
choose a license is made by github and it offers a terrible summary.

did you ever noticed github never opened its own source?

in fact, i could never find a good comparison or summary...

here's to my ongoing quest that may eventually lead to finding or making one.

my current short version: agpl is the only license banned by google and the only one that promotes complete freedom. the rest are just naive.

https://talk.ahoxus.org/tag/agpl
