### ISSUE TITLE
New posts have Scheduled mark

### ISSUE THREAD

**Issue by MasterGroosha** [writeas/writefreely#23]
I'm running WriteFreely and MySQL on the same dedicated server which has UTC+3 as its timezone. My PC from which I'm making posts is also on UTC+3.
I even performed a clean install of WriteFreely. Downloaded source code, edited `schema.sql` by adding `DROP TABLE IF EXISTS {table_name}` before any `CREATE TABLE` commands.

After going through initial setup, I open my instance and make post. It shows as "Scheduled", though it is visible for everyone. You can check it yourself by visiting `{removed}` 

I even tried re-creating instance once more and added `SET time_zone = '+03:00'` in `schema.sql`, with no luck

_Originally posted by @MasterGroosha in https://github.com/writeas/writefreely/issues/7#issuecomment-438480789_

**Comment by thebaer** [comment]
Thanks. To help debug this: what's your username on that install? So I can check out data in the API.

**Comment by MasterGroosha** [comment]
@thebaer username is duckparty

**Comment by thebaer** [comment]
Got it. So after looking at the code, the badge is showing up because the retrieved database `created` time is after the current time according to the _application_. The post is publicly showing up on the blog because it's meeting the `created <= NOW()` condition in the SQL query. (Actual scheduled posts should not be public; they should only show up for post owners.)

So it sounds like your SQL server is on a timezone ahead of your application timezone. For production use, I'd recommend putting them both on UTC. But at the very least, they should be on the same time zone (and never change) for the app to work correctly.

**Comment by MasterGroosha** [comment]
@thebaer I've just checked my datetime settings on server and both Ubuntu and MySQL server show the same datetime value.

Is WriteFreely application getting timestamp according to system timezone?

![image](https://user-images.githubusercontent.com/2780044/48512921-a7d99780-e86b-11e8-89d2-acbb79a8b297.png)

**Comment by thebaer** [comment]
Yes, the application gets it from the system timezone.

When you publish a new post, is the `created` date in the database correct?

**Comment by MasterGroosha** [comment]
As far as I see, the only place where scheduled is checked is [IsScheduled](https://github.com/writeas/writefreely/blob/8a8db3be533d990ab9f30a6ea1cffccd86b980a8/posts.go#L229) function, which calls `time.Now()` method. When calling this method in a "hello world" example, it shows me the same time in UTC+3 timezone 🤔

**Comment by thebaer** [comment]
Everything comes down to that `IsScheduled` function for showing the _Scheduled_ badge -- though the hard-coded UTC time on the frontend is a separate issue we need to address.

I just pushed a potential fix for this -- could you try building with this latest commit and seeing if that fixes the issue for you?

**Comment by MasterGroosha** [comment]
@thebaer I'm afraid I can't do this right now :( 
`go get github.com/writeas/writefreely/cmd/writefreely`
produces the error `fatal error: runtime: out of memory`

I'll try later.

**Comment by thebaer** [comment]
Yeah, unfortunately it needs a lot of memory to compile right now. Here's the [latest Linux build](https://pencil.writefree.ly/writefreely_0.3-58d163d_linux_amd64.tar.gz).

**Comment by MasterGroosha** [comment]
@thebaer Your fix seems to be working! Thank you!
