### ISSUE TITLE
main.go:119: load templates: open templates: no such file or directory

### ISSUE THREAD

**Issue by somenxavier** [writeas/writefreely#234]
After following guide, I get:

```
$ writefreely -c config.ini 
2020/01/06 22:21:54 Starting WriteFreely ...
2020/01/06 22:21:54 Loading config.ini configuration...
2020/01/06 22:21:54 Loading templates...
ERROR: 2020/01/06 22:21:54 main.go:119: load templates: open templates: no such file or directory
```

**Comment by thebaer** [comment]
Hi @somenxavier, are you running `writefreely` from the same directory where you have the `templates` directory? (And `keys` and `static`, etc.)

**Comment by somenxavier** [comment]
I just run what is written in [Getting Started](https://writefreely.org/start):

1. `writefreely --config`
1. `writefreely --gen-keys`
1. `writefreely`

**Comment by thebaer** [comment]
Great, which directory are you in? It should contain a `templates` folder. 

If it doesn't, you'll want to change into the folder where you put WriteFreely.

**Comment by thebaer** [comment]
Closing this now since this is likely isn't a bug. But please feel free to continue commenting here.

**Comment by maphew** [comment]
This can happen when running on a system which alerady has writefreely executable installed and you're not installing from scratch, e.g. a shared host. 

Go to the releases page and download the closest match, and extract the directories into where you want to run WF from. Freebsd example:

Download the latest release for MacOS. It probably doesn't matter which system though as  we're just after the templates and other resources.

	cd ~/../protected
	wget https://github.com/writefreely/writefreely/releases/download/v0.14.0/writefreely_0.14.0_macos_amd64.tar.gz
	tar -xzvf writefreely_0.14.0_macos_amd64.tar.gz
	cd writefreely
	
	# delete the MacOS executable
	rm ./writefreely

Carry on with config start and key generation. 
You'll probably also need to make the `keys` folder readable by the Web user.

	chgrp web keys keys/*
	chmod g+r keys keys/*
