### ISSUE TITLE
Run the service after mysql service

### ISSUE THREAD

**Issue by laBecasse** [writeas/writefreely#242]
I realize that the writefreely service starts with errors at the startup of my system, because there is a error of the connection to the mysql server. So, I propose to replace the service instruction on this [page](https://writefreely.org/start) by the following, which solves my problem:

```
[Unit]
Description=WriteFreely Instance
After=syslog.target network.target mysql.service

[Service]
Type=simple
StandardOutput=syslog
StandardError=syslog
WorkingDirectory=/var/www/example.com
ExecStart=/var/www/example.com/writefreely
Restart=always

[Install]
WantedBy=multi-user.target
```

Notice that I added `mysql.service`in the After list at the second iine.

**Comment by thebaer** [comment]
Thanks for bringing this up! I've added that as an option [in the documentation](https://writefreely.org/start) for anyone who has MySQL running on the same server their WriteFreely instance is running on.

Just for the future, note that you can always report documentation issues in the [github.com/writefreely/documentation](https://github.com/writefreely/documentation) repo. Thanks again for the input!
