### ISSUE TITLE
All posts display 'Invalid Date' 

### ISSUE THREAD

**Issue by mrvdb** [writeas/writefreely#253]
I just pulled `develop` and now all posts will display an 'Invalid Date' just below the title

I'm guessing (but have not tested) this is related to the latest 'local date' munging I saw flying by.

The error occurs in `static/js/localdate.js`:

`var d = new Date(dateEl.getAttribute("datetime"));`

value of the attribute was: `2019-03-05 13:12:54 +0100 CET` which indeed gives an `Invalid date` if passed into the js `Date()` constructor

Anything I missed?

**Comment by thebaer** [comment]
Thanks for the report! Which browser is that in?

**Comment by mrvdb** [comment]
Firefox

**Comment by thebaer** [comment]
Got it, thanks! Confirmed the bug and just patched in #254. Will get that merged soon.

**Comment by mrvdb** [comment]
Excellent!
