### ISSUE TITLE
Can read a private post (draft) in edit mode

### ISSUE THREAD

**Issue by darddan** [writeas/writefreely#255]
### Describe the bug

If I'm not logged in, but I know the url of a draft, I can see it's content

### Steps to reproduce (if necessary)

1. Login
2. Create and save a new draft and copy it's url (it looks something like `https:://site.com/d/random-id`)
3. Logout (or open a new incognito tab or anything)
4. (correct behaviour) go to the copied url (`https:://site.com/d/random-id`) and it shows a 404
5. (incorrect behaviour) add `/edit/` to the copied url (`https:://site.com/d/random-id/edit`) and it shows you the edit page. You can't actually edit, but now you can see the content.

### Expected behavior

What should've happened?

I would expect a 404 or some other error

### Application configuration

 - single mode 
 - sqlite
 - no open registration
 - federation disabled

**Version or last commit**:

`writefreely -v` only prints out `WriteFreely` but in my package manager it says I have version `0.11.2-2` installed

**Comment by thebaer** [comment]
Thanks for the report! Depending on your configuration, this might be correct behavior -- drafts are meant to be shareable on public instances. But we'll want to make sure visibility is consistent between the `/d/id` draft page and the `/d/id/edit` page.

What is the visibility setting of your blog (Unlisted, Private, etc.)? And what is the `private` config value set to in `config.ini`?

**Comment by darddan** [comment]
The above behaviour is from an `unlisted` instance. If I set the the instance to `private` then I can see the drafts even without the `/edit` part

**Comment by thebaer** [comment]
Hmm, that's pretty odd. You should see the same behavior either way, if you're just talking about the blog setting (as opposed to the instance setting). Is the `unlisted` instance above set to `private = true` in config.ini, or `private = false`?

**Comment by darddan** [comment]
in the config file `private` is equals to `false`. In the earlier comment (`unlisted` and `private` settings) I was talking about the publicity settings in `site.com/me/c/username`

**Comment by thebaer** [comment]
Gotcha, thanks. So from my understanding, the primary things to address here are:

* [Bug]: Ensure that unauthenticated users can't access the `/edit` page
* [Documentation]: Document the sharing abilities for drafts (writefreely/documentation#13)

Out of curiosity, is there something about how you use WriteFreely that requires completely private / unshareable drafts?

**Comment by darddan** [comment]
I use it for notes in general (drafts for private, and published for public). But I assume that's not the target audience either way. 
I added another authentication layer in nginx for the `/d/` urls if someone else uses it for the same purpose.

**Comment by thebaer** [comment]
Ah, makes sense. Yeah, we plan to support that exact use case another way, so we can keep WriteFreely focused on public content. But that's great to know!
