### ISSUE TITLE
Punycode support in handles

### ISSUE THREAD

**Issue by wakest** [writeas/writefreely#256]
I tried to make a new blog at handle xn--c1h and it silently accepted the name but deleted one of the - in the name
![image](https://user-images.githubusercontent.com/7890201/73924746-d8975980-4881-11ea-9f83-c3308b8aba28.png)

the web is a place that needs to support the worlds languages and having full punycode support through out seems like a really important step for that...

**Comment by thebaer** [comment]
Yeah, right now blog alias generation removes double (or more) hyphens. I'm sure we can make an exception for punycode aliases to solve this.

**Comment by wakest** [comment]
That would be awesome. I was just having a discussion about this issue with one of the Friendica developers, and would love to see an AP project implement Punycode username support so we can start the ball rolling on getting full non Latin based languages to be treated like equal partners in this space.

**Comment by thebaer** [comment]
Moved this to [T745](https://writefreely.org/tasks/745) since it's new functionality for us to support. Will continue tracking development there.
