### ISSUE TITLE
no mention of RSS in WriteFreely interface or Docs

### ISSUE THREAD

**Issue by wakest** [writeas/writefreely#257]
It took me a good 20 minutes of searching around to figure out where the RSS feeds to a WriteFreely blog were hidden because there is no mention of it in the [Docs](https://writefreely.org/docs/)

There is also no mention of RSS feeds in the Account Settings / Customize Blog settings. 

I eventually figured out that you can just append /feed to the url of a blog. It would be good to know what RSS features are implemented, if the feed has any options like limiting the feed to being only partial posts or full posts, how RSS feeds implement enclosures of embedded audio (can you make a podcast feed?)

**Comment by thebaer** [comment]
Thanks for bringing this up! I moved this to writefreely/documentation#14 since it's more of a documentation issue than a bug.
