### ISSUE TITLE
master account/blog vs secondary blog changability

### ISSUE THREAD

**Issue by wakest** [writeas/writefreely#258]
I just discovered you can not change the handle of a "secondary" blog on WriteFreely.

There should be some warning when setting up a secondary blog that the handle is set and there is no going back, because if you made a blog first and could change it you have now learned that blog handles are changeable and you would expect it to work a second time.

**Comment by thebaer** [comment]
Thanks for the report! I moved this [to the forum](https://discuss.write.as/t/master-account-blog-vs-secondary-blog-changability/1095) since it's more of a feature request / documentation improvement than a bug, and I responded over there.
