### ISSUE TITLE
Post link inversion

### ISSUE THREAD

**Issue by Fastidious** [writeas/writefreely#26]
I realised that, if I start a post with an `h2`, using `## Post title` the date becomes the link. Tested it on my local install, as well as on https://write.as/.

**Comment by thebaer** [comment]
Yep, this is by design -- only an `h1` / `# Title` becomes the link.

Let's discuss what you'd like to see, why you might choose a non-`h1` title (e.g. is this an aesthetic choice?), what's the expected behavior with an `h2`, `h3`, `h4`, etc. on the [forums](https://discuss.write.as/c/writefreely).
