### ISSUE TITLE
Mardown nested list rendering issue

### ISSUE THREAD

**Issue by dpc** [writeas/writefreely#27]
### Describe the bug

```
* foo
  * bar
  * baz
```

will render to:

```
<li>foo
  <ul><li>...</li></ul>
</li>
```

instead of:

```
<li><p>foo<p>
  <ul><li>...</li></ul>
</li>
```

which is more of what I'm used to.

You can see how it screws up the list: https://dpc.pw/social . After I add missing `<p></p>`, it looks OK again.

### Steps to reproduce (if necessary)

Create a post with:

```
* foo
  * bar
  * baz
```

### Expected behavior

Text should be in `<p>`? I think.

### Application configuration

NA

**Comment by thebaer** [comment]
Good catch. This is actually caused by the additional line break getting inserted in your post after `* ActivityPub:`. Will fix.
