### ISSUE TITLE
MathJax setting does not stick

### ISSUE THREAD

**Issue by mrvdb** [writeas/writefreely#28]
In blog settings, the MathJax checkbox does not work, i.e. stays 'off' after save.
 
- console gives error on jseditor not defined, but I guess that is a remnant of removing user js from write.as
- tried with 2 browsers, same result

**Comment by mrvdb** [comment]
Some more info:
- on first time setting it -> collectionattributes gets a row, but collection_id =0
- on subsequent setting -> no change

Manual change of collection_id in the table -> checkbox follows setting

**Comment by thebaer** [comment]
Thanks, and is this a single-user or multi-user setup?

**Comment by mrvdb** [comment]
Multiuser

**Comment by mrvdb** [comment]
Excellent!
