### ISSUE TITLE
Permission denied after prod setup

### ISSUE THREAD

**Issue by thepra** [writeas/writefreely#285]
### Describe the bug
I created the folder `/var/www/blog.example.com/` in which I extracted writefreely, setted up nginx and the systemd service, now starting the service gives me permission denied despite I setup the owner as www-data. Should I setup to a different owner?

### Application configuration
 - **Single mode or Multi-user mode?** Multi-user
 - **Database?** sqlite
 - **Open registration?** no
 - **Federation enabled?** yes

**Comment by thebaer** [comment]
What was the fix for this, @thepra? It's always helpful for others to know in case they run into the same issue.

**Comment by thepra** [comment]
😅 can't remember anymore, solved it but then after trying writefreely I felt it was under developed(features wide). So I left it. Sorry.

**Comment by thebaer** [comment]
No problem. Out of curiosity, which features were you missing most?

**Comment by nzjc** [comment]
I found a reasonable way around this
(Ubuntu 20 something, nginx rproxy, writefreely 1.5)
- install and configure wf with `sudo -u www-data ./writefreely config start` etc.

Previously I had been doing it as my logged in user, or as root via sudo, and that made all sorts of permissions errors bound to happen. As the site is not purely static I didn't really wanna run it all as root.
