### ISSUE TITLE
Setup with reverse proxy leads to some static GET to localhost:[port] instead of the root domain

### ISSUE THREAD

**Issue by thepra** [writeas/writefreely#286]
### Describe the bug
As in the title, after setting up the writefreely server from the guide I found that out of the gate some resource were still pointing to localhost as if they were hard setup, like:
![image](https://user-images.githubusercontent.com/7032509/77233326-1688dc80-6ba7-11ea-88bf-215d42575803.png)

Bug number 2 is that error appearing in the h.js which you should look up(from Firefox latest release).

### Steps to reproduce (if necessary)
1. Setup writefreely with reverse proxy
2. Open the website
3. Look at the console for errors

### Expected behavior
What should've happened?
Right out of the box have pointing to static resources done right. And JS without error.

### Application configuration
 - **Single mode or Multi-user mode?** Multi-user
 - **Database?** sqlite
 - **Open registration?** no
 - **Federation enabled?** yes

**Version or last commit**: 0.11.2

**Comment by thepra** [comment]
One solution could be that at the `writefreely --config` step there is also an option that asks if the writefreely server is going to be behind a reverse proxy, and if so, switch from pointers from localhost:[port] to blog.example.com

**Comment by thebaer** [comment]
Thanks for bringing this up, @thepra. What is your `host` config value? If it's set to `localhost` and you intend this to be accessed outside the local machine, you'll want to instead set it to the public-facing URL ([see config docs](https://writefreely.org/docs/latest/admin/config#app) for more info). Based on your screenshots, it should probably be `https://blog.[redacted-domain]`

**Comment by thebaer** [comment]
Closing for now. Please let us know if this turns out to be something other than a misconfiguration.
