### ISSUE TITLE
Huge inter-lines spaces on Chrome for android

### ISSUE THREAD

**Issue by Clovis-Portron** [writeas/writefreely#290]
### Describe the bug
Originally brought on [Mastodon](https://mstdn.fr/@Clovis/103906883497600654)
On some(?) version(s) of Chrome for Android, it appears that there is huge inter-lines spaces making the reading really hard. 
![Bug thumbnail](https://static.mstdn.fr/static/media_attachments/files/002/812/236/original/bd3037e8c4c682f8.png)

I would label this issue as "bug" since apparently, this only happens on some version of Chrome for Android.

### Steps to reproduce (if necessary)
1. On Chrome for Android (Chrome 80.0.3987.149 for Android)
2. Go to https://write.as/kamen-reader/issue-10-hymenoptere-a-claques

### Expected behavior
The interline space should be way smaller. 
![expected behavior](https://static.mstdn.fr/static/media_attachments/files/002/807/923/original/6ce5a50fbf81ad4a.png)

I played a bit with Chrome remote debug tools, and here is what I found:
The issue seems to be linked to these css lines: 
`#post article.norm {
 line-height: 1.5;
}`

Changing it for `line-height: normal` seems to correct the problem.
![Correct](https://static.mstdn.fr/static/media_attachments/files/002/812/241/original/99b34387d0f216ec.png)

But to keep the relation between user font-size parameters, we can use em units for example `line-height: 0.6em`.
![With em](https://static.mstdn.fr/static/media_attachments/files/002/812/270/original/6a10a1089e8250e8.png)

After discussion, I would be happy to propose a MR :)

**Comment by thebaer** [comment]
Thanks for opening an issue for this!

Before making any changes, I'd like to confirm that this affects more people, and that updating the `line-height` is the correct solution. To do that, we'll need to be able to replicate this -- I'm also running Chrome 80.0.3987.149 on Android but am unable to get the same results.

Can anyone else confirm they're seeing this issue?

**Comment by Clovis-Portron** [comment]
If it can help, I'm running Android 7.0; Huawei VNS-L31

**Comment by thebaer** [comment]
Closing this since we haven't heard about this issue from anyone else. Please feel free to reopen if anyone can replicate!
