### ISSUE TITLE
Invalid JSON-LD syntax; @context must be an object.

### ISSUE THREAD

**Issue by wiwie** [writeas/writefreely#296]
When following my writefreely user chris@blog.cwiwie.org from friendica chris@friendica.cwiwie.org I get the following error response upon writing new posts / updating posts in writefreely:

` 2020/04/10 22:51:59 Response: JsonLdException: [jsonld.SyntaxError]: Invalid JSON-LD syntax; @context must be an object. `

From the json-ld spec it also seems that the context is supposed to be an object or a link to a jsonld file: https://www.w3.org/TR/2020/CR-json-ld11-20200316/#the-context

**Comment by wiwie** [comment]
This is the JSON ld in question:

```
{
  "@context": [
    "https://www.w3.org/ns/activitystreams"
  ],
  "type": "OrderedCollectionPage",
  "id": "https://blog.cwiwie.org/api/collections/chris/outbox?page=1",
  "totalItems": 3,
  "partOf": "https://blog.cwiwie.org/api/collections/chris/outbox",
  "next": "https://blog.cwiwie.org/api/collections/chris/outbox?page=2",
  "orderedItems": [
    {
      "@context": [
        "https://www.w3.org/ns/activitystreams",
        {}
      ],
      "type": "Create",
      "id": "https://blog.cwiwie.org/api/posts/5pfxj55e0l",
      "actor": "https://blog.cwiwie.org/api/collections/chris",
      "published": "2020-04-10T21:25:51+02:00",
      "object": {
        "type": "Article",
        "id": "https://blog.cwiwie.org/api/posts/5pfxj55e0l",
        "published": "2020-04-10T21:25:51+02:00",
        "inReplyTo": null,
        "url": "https://blog.cwiwie.org/asdasd-asdsdd-sdds",
        "attributedTo": "https://blog.cwiwie.org/api/collections/chris",
        "to": [
          "https://www.w3.org/ns/activitystreams#Public"
        ],
        "cc": [
          "https://blog.cwiwie.org/api/collections/chris/followers"
        ],
        "name": "asdasd asdsdD SDDS",
        "content": "<p><img src=\"https://wolke.cwiwie.org/s/syTTsZob3J66HW4/preview\" alt=\"Test Image\"></p>\n",
        "contentMap": {
          "en": "<p><img src=\"https://wolke.cwiwie.org/s/syTTsZob3J66HW4/preview\" alt=\"Test Image\"></p>\n"
        },
        "tag": []
      }
    },
    {
      "@context": [
        "https://www.w3.org/ns/activitystreams",
        {}
      ],
      "type": "Create",
      "id": "https://blog.cwiwie.org/api/posts/eiftt4yilf",
      "actor": "https://blog.cwiwie.org/api/collections/chris",
      "published": "2020-04-10T19:54:40+02:00",
      "object": {
        "type": "Article",
        "id": "https://blog.cwiwie.org/api/posts/eiftt4yilf",
        "published": "2020-04-10T19:54:40+02:00",
        "inReplyTo": null,
        "url": "https://blog.cwiwie.org/the-whole-screen-is-covered",
        "attributedTo": "https://blog.cwiwie.org/api/collections/chris",
        "to": [
          "https://www.w3.org/ns/activitystreams#Public"
        ],
        "cc": [
          "https://blog.cwiwie.org/api/collections/chris/followers"
        ],
        "name": "the whole screen is covered",
        "content": "<p>with the left side</p>\n",
        "contentMap": {
          "de": "<p>with the left side</p>\n"
        },
        "tag": []
      }
    },
    {
      "@context": [
        "https://www.w3.org/ns/activitystreams",
        {}
      ],
      "type": "Create",
      "id": "https://blog.cwiwie.org/api/posts/jt8lfz6mko",
      "actor": "https://blog.cwiwie.org/api/collections/chris",
      "published": "2020-04-10T19:27:58+02:00",
      "object": {
        "type": "Article",
        "id": "https://blog.cwiwie.org/api/posts/jt8lfz6mko",
        "published": "2020-04-10T19:27:58+02:00",
        "inReplyTo": null,
        "url": "https://blog.cwiwie.org/test-post",
        "attributedTo": "https://blog.cwiwie.org/api/collections/chris",
        "to": [
          "https://www.w3.org/ns/activitystreams#Public"
        ],
        "cc": [
          "https://blog.cwiwie.org/api/collections/chris/followers"
        ],
        "name": "Test Post",
        "content": "<p>bla test.</p>\n\n<p>_ Blubb _</p>\n\n<p><img src=\"https://wolke.cwiwie.org/s/syTTsZob3J66HW4/preview\" alt=\"test image\"></p>\n",
        "contentMap": {
          "de": "<p>bla test.</p>\n\n<p>_ Blubb _</p>\n\n<p><img src=\"https://wolke.cwiwie.org/s/syTTsZob3J66HW4/preview\" alt=\"test image\"></p>\n"
        },
        "tag": []
      }
    }
  ]
}
```

**Comment by thebaer** [comment]
Hey, thanks for the report. I thought this was a bug at first, but I'm not sure based on the information here. [Further down](https://www.w3.org/TR/2020/CR-json-ld11-20200316/#example-5-referencing-a-json-ld-context) on the page you referenced:

> Contexts can either be directly embedded into the document (an embedded context) or be referenced using a URL.

And you can confirm other AP platforms like Mastodon produce similar JSON-LD.

I'm sure we could clean up the extra `@context`s in the JSON you provided, and maybe change from an array to a string at the top-level of the document (since we aren't extending the definition), but otherwise might be something on Friendica's end.

**Comment by annando** [comment]
Friendica is compacting the JSON-LD input before processing. This compacting is done via a JSON-LD library (and it only works when the JSON-LD itself is valid). This also means that we are more picky like other projects, but this compacting makes the parsing easier for us.

I still have to have a deeper look at this issue. But when I found out that it isn't an issue on our side, it would be great if you could apply some changes on some development machine and that I could check it from our side, just to make sure that everything is okay.

**Comment by annando** [comment]
I just had a look at the outboxes of other projects. Mastodon for example isn't providing a `@context` for each entry in the outbox - and I think that this is the correct behaviour.

**Comment by thebaer** [comment]
Yep, just removed those fields on [outboxes](https://pencil.writefree.ly/api/collections/hello/outbox?page=1) on our [test instance](https://pencil.writefree.ly). If you need to create an account for testing there, [here's an invite link](https://pencil.writefree.ly/invite/7MCrq3).

Let me know if that fixes the issue, or if we need to make any other changes.

**Comment by annando** [comment]
The outbox looks fine now. And I just signed up and got the most beautiful error message I ever got:

> Server error 😵
>
> Please contact the human authors of this software and remind them of their many shortcomings.
> 
> Be gentle, though. They are fragile mortal beings.
> 
> Also, unlike the AI that will soon replace them, you will need to include an error log from the server in your report. (Utterly primitive, we know.)
> 
> – Pencil 🤖

**Comment by thebaer** [comment]
Haha, whoops! Needed to mess with the database. That should be fixed now if you want to try again.

**Comment by thebaer** [comment]
@annando Just to confirm, did that outbox change fix everything on Friendica's end?

**Comment by annando** [comment]
I guess so, but I will perform some tests with the test account.

**Comment by thebaer** [comment]
Sounds good. Just merged the fix in #299, so if everything looks good on your end we can close this.

**Comment by wiwie** [comment]
I can confirm that this fixes it for me. Should we close this issue or do you want to perform some further testing @annando?

**Comment by annando** [comment]
@wiwie when it works for you, it's great. I want to do several communication tests.

**Comment by thebaer** [comment]
I'll close this for now, since we seemed to have fixed this particular issue. But if anything comes up in your testing @annando please feel free to open a new issue, or continue the discussion here!
