### ISSUE TITLE
Please be consistent with version and tag names

### ISSUE THREAD

**Issue by SamWhited** [writeas/writefreely#30]
Currently if a version is a .0 release the release is, eg. 0.3 and the tag is v0.3.0. This makes for download URLs such as:

https://github.com/writeas/writefreely/releases/download/v0.3.0/writefreely_0.3_linux_amd64.tar.gz

during packaging, it would be nice if these were the same so that users don't have to store two different versions. Eg. if it were:

https://github.com/writeas/writefreely/releases/download/v0.3.0/writefreely_0.3.0_linux_amd64.tar.gz

instead a single variable could be used to substitute for both. It's a minor annoyance, but I'd appreciate it if these could be consistent in the future all the same.

Thanks for your consideration.

**Comment by thebaer** [comment]
Thanks for mentioning this. I need to automate things more, but either way I'll be sure it's named this way going forward (starting with v0.3.0 -- I've renamed the assets).
