### ISSUE TITLE
Markdown reference links in excerpts don't render correctly

### ISSUE THREAD

**Issue by Filius-Patris** [writeas/writefreely#304]
### Describe the bug
A post which has a link in the from of `[name]` and at the end of the page `[name]: example.com`. After the first sentence (with the link) insert a `<!--more-->` content wall.

### Expected behavior
The link should be clickable in the excerpt

### Application configuration
 - **Single mode mode** 
 - **Database: sqlite**
 - **Open registration: no**
 - **Federation enabled: yes**

**Version or last commit**:
0.12

EDIT: The right term is "excerpt", not "preview".

**Comment by thebaer** [comment]
Thanks for reporting this, @Filius-Patris! To be sure, what do you mean by "markdown preview"? The text returned from the `/api/markdown` endpoint?

**Comment by Filius-Patris** [comment]
I meant the frontpage of the blog, where only the text up to `<!--more-->` is shown. I don't know about the `/api/markdown` endpoint (it yields 404 for me).

This image shows it:
![image](https://user-images.githubusercontent.com/37048904/80405846-791a7a00-88c3-11ea-8494-08f84515d312.png)
This is what appears on the frontpage feed, but if I click on the post, the link renders correctly. The link destination to `[codeberg]` is provided at the end of the markdown text.

**Comment by Filius-Patris** [comment]
The workaround is quite simple though: Just put the link destination directly after the text (the `[name](destination)` syntax).
Now that I'm aware of it, I can just put all links needed in the preview in there directly.
It might confuse newbies like me, but if you want, you can close the issue as the workaround is trivial.

**Comment by SayedDubai** [comment]
I am using https://write.tedomum.net/ but i don't know how to add pictures to my post and how to add links

**Comment by Filius-Patris** [comment]
If you're searching for general help how to add images/links somewhere in the post (not just in the excerpt), you may be on the wrong thread.

Check out this resource: https://writefreely.org/docs/latest/writer/writing.md

**Comment by thebaer** [comment]
Thanks for the details, @Filius-Patris. Some people have discussed this a bit before [on the forum](https://discuss.write.as/t/footnote/172), and I'd generally like to keep encouraging the officially-supported `[name](destination)` syntax. 

However, if you or anyone else is interested in working on support for footnotes / reference links, please feel free to open a pull request, or start a forum discussion if you need help with implementation. We'd be happy to accept any improvements here!
