### ISSUE TITLE
"No to!" in the logs

### ISSUE THREAD

**Issue by Crocmagnon** [writeas/writefreely#311]
### Describe the bug
I noticed some errors in the logs (`No to! <nil>`), see: https://gist.github.com/Crocmagnon/b54664133aed86127f2133bdb5f099d3

### Steps to reproduce (if necessary)
Let  the app run, with federation enabled?

### Expected behavior
I shouldn't get this message in the logs? Or it should be more explicit.

### Application configuration
 - **Single mode or Multi-user mode?** single
 - **Database?** sqlilte
 - **Open registration?** no
 - **Federation enabled?** yes

**Version or last commit**: 037fc40 but happened also with v0.12.0

**Comment by thebaer** [comment]
Thanks @Crocmagnon. This would have more useful information with the `--debug` flag enabled, so I've changed it to only log this message when that's turned on in #312.

**Comment by Crocmagnon** [comment]
👍 and what's that error message supposed to mean?

**Comment by Crocmagnon** [comment]
I mean, should I do something about it? Is there something not working on my instance?

**Comment by thebaer** [comment]
It refers to the `to` attribute on ActivityPub requests -- it's only needed for development / debugging, so nothing for you to worry about. Whatever activity is triggering the message is simply going ignored.

**Comment by Crocmagnon** [comment]
Thanks for your answer, patience and speed! 😊
