### ISSUE TITLE
TestPostLede fails

### ISSUE THREAD

**Issue by Bridouz** [writeas/writefreely#316]
Trying to package `writefreely` for Alpine Linux (busybox/musl libc)
Build is OK but Tests fail at :

```
=== RUN   TestPostLede
    TestPostLede: posts_test.go:34: #2: Got 'Sup? Everyone says punctuation is punctuation.' from 'Sup? Everyone says punctuation is punctuation.'; expected 'Sup?'
--- FAIL: TestPostLede (0.00s)
```

Packaging is using :
 
```
make build
make test
```

Requirements are `go, go-bindata, sqlite, nodejs-less, nodejs-less-plugin-clean-css"

**Version or last commit**:
  - `v0.12.0`

**Comment by thebaer** [comment]
Thanks for the report, @Bridouz! A fix should be pretty straightforward -- in the `PostLede` func, we just need to look for the `?` character. 

For anyone interested in fixing this, feel free to open a pull request!
