### ISSUE TITLE
How to enable OAuth 2 in v 0.12

### ISSUE THREAD

**Issue by idelem** [writeas/writefreely#320]
This may be a stupid question, but how can I enable OAuth 2 for my site?

I just upgraded to v 0.12.0 and got completely lost on the new OAuth 2 feature. I don't see the slack/gitlab login buttons on the login page. Fiddling with admin settings doesn't solve the problem. Searching through forum threads and issues isn't of much help. I think I might be missing something deadly simple here but I don't know which...

**Comment by thebaer** [comment]
Thanks for bringing this up, @idelem. This issue tracker is only for bug reports, so let's move this discussion to writefreely/documentation#30.
