### ISSUE TITLE
static assets served without cache policy leads to suboptimal page speed

### ISSUE THREAD

**Issue by freddyb** [writeas/writefreely#322]
### Describe the bug
Static assets (list below) are served without any caching header, which results in the browser re-requesting the files too often.

> /fonts/Lora-Bold.woff2
> /fonts/Lora-Regular.woff2
> /fonts/open-sans-v13-latin-regular.woff2
> /js/webfont.js
> /js/h.js
> /js/postactions.js
> /js/localdate.js
> /css/fonts.css

### Steps to reproduce (if necessary)
1. Open Browser (e.g., Firefox) Developer Tools and its network panel
2. Load a writefreely instance
3. Observe response headers

### Expected behavior
writefreely server should have responded with a cache header

### Application configuration
 - **Single mode or Multi-user mode?** single
 - **Database?** [mysql/sqlite] mysql
 - **Open registration?** [yes/no] no
 - **Federation enabled?** [yes/no] no

**Version or last commit**:
v0.12.0

**Comment by thebaer** [comment]
Thanks for reporting this, @freddyb! I'm sure we can tweak the Go file server to include the right headers.

If anyone wants to work on this, please feel free to open a pull request!
