### ISSUE TITLE
Docker refactor

### ISSUE THREAD

**Issue by shleeable** [writeas/writefreely#323]
`docker-compose up -d db`
`docker-compose exec db sh -c 'exec mysql -uroot -pwritefreely writefreely < /tmp/schema.sql'`

docker exec writefreely_web_1 writefreely --gen-keys
docker exec -it writefreely_web_1 writefreely --config

**Comment by thebaer** [comment]
Thanks -- would you mind opening a pull request with this fix?

**Comment by shleeable** [comment]
I'll PR once I've got it all working.

**Comment by thebaer** [comment]
Is this related to work in #357?
