### ISSUE TITLE
Whitelist Footer Element

### ISSUE THREAD

**Issue by cjeller1592** [writeas/writefreely#326]
### Describe the bug
 If you publish a post with the `footer` HTML element, it's stripped from the post. 

_Context_: I am trying to use a web extension's embed feature ([Quotebacks](https://quotebacks.net)) that's code requires the manipulation of the embed's footer. Since the footer gets stripped from the post, the code cannot find the footer and doesn't render properly.

### Steps to reproduce (if necessary)
1. Publish a post with a `<footer></footer>` element
2. Inspect the post in browser tools
3. Notice how the footer element in the post is gone

### Expected behavior
The footer element should have stayed intact when you inspect the post.

**Comment by thebaer** [comment]
Thanks for reporting this! While we're at it, we might as well support the `<header>` element, too.

This should be a pretty straightforward fix -- simply add:

```go
policy.AllowElements("header", "footer")
```

in this func:

https://github.com/writeas/writefreely/blob/5c94d23466dc3e7e1821b845d9d7db9294c48af4/postrender.go#L171-L184
