### ISSUE TITLE
Weird footnote display

### ISSUE THREAD

**Issue by dangom** [writeas/writefreely#33]
### Describe the bug
Sometimes the following, in a markdown file:
```
<sup>
    <a id="fnr.1" class="footref" href="#fn.1">1</a>
</sup>
```

Will be transformed into the following html:
```
<sup>
    <a id="fnr.1" class="footref">
        <span>#</span><span class="p-category">fn</span>
    </a>.1”&gt;1
</sup>
```

Some weird interaction of the href hashtag?

### Steps to reproduce (if necessary)
Not sure. In a minimal markdown file things worked ok, so I couldn't reproduce. But checkout broken footnote links [here](https://write.as/dani/writing-a-phd-thesis-with-org-mode).

### Expected behavior

Instead of being displayed like:
<sup><a id="fnr.1" class="footref"><span>#</span><span class="p-category">fn</span></a>.1”&gt;1</sup>

The footnote link would be:
<sup><a id="fnr.1" class="footref" href="#fn.1">1</a></sup>

**Comment by thebaer** [comment]
Fixed in #43

**Comment by dangom** [comment]
This is awesome. When should we expect the changes to land on write.as?!

**Comment by thebaer** [comment]
It's live now! :)

**Comment by eternaltyro** [comment]
> ```
> [1](my-slug#fn.1)
> ```

Is this behavior documented? I'm trying to figure out how to add footnotes.
