### ISSUE TITLE
db migrate command error

### ISSUE THREAD

**Issue by misaka00251** [writeas/writefreely#337]
### Describe the bug

```
$ ./writefreely db migrate
2020/07/24 12:06:19 Loading config.ini configuration...
2020/07/24 12:06:19 Connecting to mysql database...
2020/07/24 12:06:19 Migrating to V4: support oauth
2020/07/24 12:06:19 Closing database connection...
ERROR: 2020/07/24 12:06:19 main.go:121: migrate: Error 1050: Table 'oauth_users' already exists
```

### Steps to reproduce (if necessary)
1. Download 0.12.0
2. `ALTER DATABASE writefreely CHARACTER SET latin1 COLLATE latin1_swedish_ci;`
3. `./writefreely db migrate`

### Expected behavior
Migrate success?

### Application configuration
 - **Single mode or Multi-user mode?** Single
 - **Database?** mysql

**Version or last commit**:
0.12.0

**Comment by thebaer** [comment]
Hmm, it's hard to tell exactly what's going on. But can you try running this database query and then trying `writefreely db migrate` again?

```sql
DROP TABLE oauth_users;
```

(Related: https://github.com/writeas/writefreely/issues/302#issuecomment-619056735)

**Comment by misaka00251** [comment]
Yes! it work.
