### ISSUE TITLE
developer discussion on footnotes: implementation and feature behavior

### ISSUE THREAD

**Issue by jzacsh** [writeas/writefreely#338]
sorry Matt, i tried to post to the forum, but Discuss gave me an error about not being allowed to use links because i'm new on discuss 🤷 (feel free to delete this post or (better) transfer for me to the forum). i figured better to post helpful discussion somewhere wrong than not at all.

---

## footnotes: background on the feature

The best explanation I've seen on why-not and what-next for foot notes is Matt's summary here: https://discuss.write.as/t/footnote/172/8 (it's also the most updated per [this recent comment](https://github.com/writeas/writefreely/issues/304#issuecomment-663046369) and my forum search)

> [The [excerpt/read-more feature](https://howto.write.as/show-an-excerpt)] simply truncates the post and renders the markdown
> on the initial excerpt. To fix [the lack of footnotes], we’ll need to render the markdown based
> on the entire post, truncate it at the  `<!--more-->`  tag, and make sure the footnotes
> option in the `writeas/saturday`  library is enabled.

-- [Matt, 2019-02](https://discuss.write.as/t/footnote/172/8)

## goal: outline detail for development

The goal of this thread is just want to expand[^1] on Matt's thread - hopefully get Matt's input - on what exactly is needed, maybe even with code pointers.

As a bonus, since this has been unimplemented so long, it might be helpful to add its status to the end-user documentation (there's both a `howto` site and a `guides` site - not sure which).

## details expanded
- _Q1_: where does the platform's markdown logic begin in write.as codebase?
   - _A_: I think at [this `blackfriday.Markdown(...)` call][parsingStarts]?
   - From the post above, I'm guessing we eventually need to pass [`EXTENSION_FOOTNOTES` const][libraryFlag] into [this list][flagPassing].
- _Q2_:  where does the conflicting feature ("excerpt/more") begin in write.as codebase?
  - _A_: **TBD**
- _Q3_(**TBD**): how to handle above-the-fold footnotes.

     I could be mistaken - feel free to correct me. I'm guessing **rendering footnotes as-is for excerpt mode would cause link bugs**. Seems we'd cause a bug where we'd expose an anchor tag (say from the list view of a blog) with `#fn-1`, that doesn't actually have a corresponding destination ont hat page (the list-view of the blog).
  - _A1_: (guessing this is easier) in the "excerpt" rendering, strip the anchor tag from around the super-script of the footnotes.
    - _maybe just render twice instead of truncating?_
      This approach makes me think Matt's initial algorithm outline is maybe _not_ what he'd want to go with (why hackily strip out footnotes when you can just render the post twice: once for truncated view, once for full view - the former with the flag not passed in, the latter where the flag *is* passed in)
  - _A2_: (guessing this is harder) in the "excerpt" rendering, transform the `href` of the anchor tag to be absolute (eg: instead of being a link like `#fn-1` it should be `https://full-blog.domain/...#fn-1`).
    - *questionable value*.
      Not only is this probably more work, but I'm guessing it's of minimal value, as following a footnote from excerpt-rendering means you're not fully engaged in the content yet. so my gut say this isn't the right choice.

[libraryFlag]: https://github.com/writeas/saturday/blob/392b95a033203c3118dfa69a1077d62b5c7a53c6/markdown.go#L42
[parsingStarts]: https://github.com/writeas/writefreely/blob/793380c1d9ea43a2ca125dbb45d4f6a99cd33685/postrender.go#L118
[flagPassing]: https://github.com/writeas/writefreely/blob/793380c1d9ea43a2ca125dbb45d4f6a99cd33685/postrender.go#L67-L72

Hopefully this'll be  a helpful post. I'll come back when I have time. Anyone should feel free to implement though :) I'm not claiming I will just yet.

----

[^1]: I'm thinking if *I* ran into such clear instructions, I'd maybe just try to implement it real quick and send the pull request. Maybe this thread will move the ball forward one roll, and let someone else do that.

**Comment by jzacsh** [comment]
Ah, Q2's answer I think is these [two calls to render markdown][twoMarkdownCalls] lines 51 and 53:

```go
	p.HTMLContent = template.HTML(applyMarkdown([]byte(p.Content), baseURL, cfg))
	if exc := strings.Index(string(p.Content), "<!--more-->"); exc > -1 {
		p.HTMLExcerpt = template.HTML(applyMarkdown([]byte(p.Content[:exc]), baseURL, cfg))
	}
```

This makes me think Q3's A1 appraoch is the way to go.

Line 51 (in the blob-specific link I gave) would always take the extension as an argument, and line 53 would never take the extension as an argument.

[twoMarkdownCalls]: https://github.com/writeas/writefreely/blob/793380c1d9ea43a2ca125dbb45d4f6a99cd33685/postrender.go#L51,L53

**Comment by jzacsh** [comment]
Oh, but I guess _not_ passing the extension into the second call wouldn't render superscript at all, it'd render the raw `[^foo]` markdown..

... so maybe turning these into absolute links is the way to go? (Q3's A2 approach)
... or maybe implement a blackfriday feature to make text-only footnotes (so they render as superscript _without_ the anchor wrapping them)?

**Comment by thebaer** [comment]
Thanks for starting this discussion, @jzacsh! I went ahead and moved everything over to [this forum thread](https://discuss.write.as/t/developer-discussion-on-footnotes-implementation-and-feature-behavior/1663). I also adjusted things on the forum so you shouldn't run into those limits anymore. I'll close this issue and we can continue the conversation over there.
