### ISSUE TITLE
Meta tags are double html-encoded

### ISSUE THREAD

**Issue by thebaer** [writeas/writefreely#340]
### Describe the bug

If you check the HTML source [on this post](https://mikestone.me/twitter-got-hacked-is-mastodon-immune), the HTML <meta> tags are double HTML encoded. For example:

```html
<meta property="og:description" content="Unless you&amp;#39;ve been hiding under a rock the last week or so, you probably know that Twitter got &amp;#34;hacked&amp;#34;. So, is Mastodon immu..." />
```

### Expected behavior

The `&amp;#34;` should be `&#34;`

### Application configuration
 - **Single mode or Multi-user mode?** multi-user
 - **Database?** n/a
 - **Open registration?** n/a
 - **Federation enabled?** n/a

**Version or last commit**: v0.12

**Comment by Obayanju** [comment]
I think you meant `&#39;` for a single quote since the linked post uses a single quote.
