### ISSUE TITLE
Edit, pin, delete, change to draft links next to post title in post listing not accessible on mobile browser

### ISSUE THREAD

**Issue by wiwie** [writeas/writefreely#359]
When browsing the list of posts on my single user instance, and hovering the title of a post links to edit, delete, pin, and change to draft appear next to the title.

This hover behaviour is not applicable to mobile browsers.

A workaround is to long press on any of these links (hitting by chance in the dark) and then closing the appearing context menu. Then the links are shown as well (at least with Chromium on Android).

**Comment by wiwie** [comment]
My proposal is that the links should always be shown on mobile browsers.

**Comment by thebaer** [comment]
Thanks for the report and suggestion, @wiwie! This has been brought up in #309, so let's move the discussion there.
