### ISSUE TITLE
Tag starting with a number is not converted into a clickable link

### ISSUE THREAD

**Issue by cblte** [writeas/writefreely#361]
### Describe the bug
When writing a post, every tag starting with a number is not converted into a a clickable link. But when you enter it as a url in the adressbar, all posts with this tag are shown.

### Steps to reproduce (if necessary)
1. create a new post
2. add some text and a tag. e.g.: #100DaysToOffload
3. saving the post and moving it from drafts to the blog
4. tag is not clickable 

### Expected behavior
The Tag should be converted to a clickable link as all other tags as well

### Application configuration
 - **Single mode** 
 - **Database?** [sqlite]
 - **Open registration?** [no]
 - **Federation enabled?** [yes]

**Version or last commit**:
Latest official Relase from 22 Apr: Writefreely 0.12.0

**Comment by thebaer** [comment]
Thanks for the detailed report! This was actually fixed in #307, and will be included in our next release.
