### ISSUE TITLE
Custom style does not apply on the blog pages

### ISSUE THREAD

**Issue by OniriCorpe** [writeas/writefreely#372]
### Describe the bug
The custom style does not apply on the blog pages, only on the home page.

### Steps to reproduce
Apply a custom style in the settings, for example:
```
article p {
  text-indent: 2em;
}
```
Check the home page : ✅ 
On https://EXAMPLE.TLD/ : it's all right.

Check the blog pages : ❌
On https://EXAMPLE.TLD/chapter-1/ : Nothing's changed.

### Expected behavior
Style changes should be applied to all of the user's posts.

### Application configuration
 - **Single mode** 
 - **Database?** mysql
 - **Open registration?** no
 - **Federation enabled?** yes

**Version or last commit**: v0.12.0

**Comment by cjeller1592** [comment]
Applying similar style on the blog pages as the home page requires specifying the home page (collection) and blog pages (post) ID in the CSS.

```CSS
#collection, #post article {text-indent: 2em;}
```
Let me know if that works on your end @OniriCorpe. There definitely should be more documentation on this. For now there's the basic CSS guide (but a lot more could be explained in it) here: https://writefreely.org/docs/latest/writer/css

I wonder if this is more of a documentation problem.

**Comment by cblgh** [comment]
@cjeller1592 Hi! I just came across the project and was excited to see that a federated Blogger already existed. Is the theming possible on a blog-per-blog basis, or is it restricted to one theme per WriteFreely instance?

**Comment by cjeller1592** [comment]
You're right @cblgh, theming is on a blog-per-blog basis!

I am going to close this issue due to inactivity. Please feel free to open a new one if something else doesn't make sense with customization.

**Comment by cjeller1592** [comment]
You're right @cblgh, theming is on a blog-per-blog basis!

I am going to close this issue due to inactivity. Please feel free to open a new one if something else doesn't make sense with customization.
