### ISSUE TITLE
Can't announce articles from writefreely instances on litepub

### ISSUE THREAD

**Issue by kaniini** [writeas/writefreely#4]
Announcing a post fails on litepub because the given object URI cannot be reused.  This is technically a violation of both ActivityPub as well as LitePub standards.

```
05:35:17.818 [info] {
  "type": "Undo",
  "to": [
    "https://pleroma.site/users/kaniini/followers",
    "https://pleroma.site/users/kaniini"
  ],
  "published": "2018-11-10T05:34:53.551223Z",
  "object": {
    "type": "Announce",
    "to": [
      "https://pleroma.site/users/kaniini/followers",
      "https://blog.writefreely.org/api/collections/writefreely"
    ],
    "published": "2018-11-10T05:34:07.348041Z",
    "object": "https://blog.writefreely.org/api/posts/84rth4rg4b1ksw9x",
    "id": "https://pleroma.site/activities/6c918db7-5940-43de-93a5-4408bedfc7c8",
    "context_id": 14964830,
    "context": "https://pleroma.site/contexts/df27ab3f-9660-4f9f-ad2c-1dd51a5ca220",
    "cc": [
      "https://www.w3.org/ns/activitystreams#Public"
    ],
    "actor": "https://pleroma.site/users/kaniini"
  },
  "id": "https://pleroma.site/activities/5aea13d6-683a-4927-8cc4-8bde293a7383",
  "context_id": 14964830,
  "context": "https://pleroma.site/contexts/df27ab3f-9660-4f9f-ad2c-1dd51a5ca220",
  "cc": [
    "https://www.w3.org/ns/activitystreams#Public"
  ],
  "actor": "https://pleroma.site/users/kaniini",
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    "https://litepub.github.io/litepub/context.jsonld"
  ]
}
```

We can prove the object is not reusable by trying to fetch it as we would any other capability URI:

```
raccoon:~$ curl -H 'Accept: application/json' 'https://blog.writefreely.org/api/posts/84rth4rg4b1ksw9x'
404 page not found
raccoon:~$ curl -H 'Accept: application/activity+json' 'https://blog.writefreely.org/api/posts/84rth4rg4b1ksw9x'
404 page not found
raccoon:~$ curl -H 'Accept: application/ld+json; profile="https://www.w3.org/ns/activitystreams"' 'https://blog.writefreely.org/api/posts/84rth4rg4b1ksw9x'
404 page not found
```

It's a shame because I wanted to share your FOSS announcement with the world.

**Comment by thebaer** [comment]
So to fix this you just need to be able to fetch posts like you're doing in those cURL requests? I think this is just a missing route on our end.

**Comment by kaniini** [comment]
yeah, the object URIs need to respond with the underlying `Article` object.  if they respond with 404 or otherwise, a litepub instance must consider the `Announce` as denied.  Mastodon also has the same behavior.

**Comment by thebaer** [comment]
Got it, thanks for the explanation. I have noticed some occasional weirdness with `Announce`s for a while, so that might've been the issue. Just deployed the fix on blog.writefreely.org

**Comment by thebaer** [comment]
Ah, whoops. Data isn't correct.

**Comment by kaniini** [comment]
yeah, it seems to be returning your own internal data for the post instead of the AS2 object.

**Comment by thebaer** [comment]
Alright, should all work now.

**Comment by kaniini** [comment]
Seems the boost is still failing.  Digging into it some more.

**Comment by kaniini** [comment]
Okay.  Looks like it's good on writefreely end.  The failure I am seeing now is caused by failure to reflect WriteFreely articles into OStatus, but that's something we need to fix in Pleroma.  Feel free to close this out.

**Comment by thebaer** [comment]
Cool, will leave this closed :+1: Thanks for investigating.

**Comment by kaniini** [comment]
Yep, with an OStatus reflection hotfix it all works as expected.

**Comment by kaniini** [comment]
(and it looks so nice in Pleroma: https://pleroma.site/notice/8016720)

**Comment by thebaer** [comment]
Awesome. Yeah, it looks really good. Love that links and text formatting show up too.
