### ISSUE TITLE
After update through API, editor shows old content 

### ISSUE THREAD

**Issue by mrvdb** [writeas/writefreely#41]
When updating a post through the API while also checking the editor on the website, the editor does not use the updated content which came in, but seems to be using a local browser storage entry `draft......` to show the editable content.

Steps to reproduce the behavior (I have used the writefreely.el package):
1. Create a post through the api as draft
2. Got to the site, find the post and edit
3. Do other things on site
4. Post update through api
5. Go back to post and edit

Editor will show initial content created in 1. or, if applicable any changes made in the editor in step 2. (but not published)

### Expected behavior
Post should be updated according to latest update through api. It looks as if the local storage does not get invalidated properly.

### Application configuration
- Multi-user / open reg / federation enabled
- latest git version

**Comment by thebaer** [comment]
Thanks for the report -- definitely need to fix this.

We'll need to keep track of the last time the draft in the editor was modified (in localStorage), and then compare it with the `Updated` time on the post when loading the editor. If the published post was updated since the draft was last modified, then we'll erase the draft in localStorage and load the most recent post data from the server.

**Comment by wiwie** [comment]
I am not sure whether this is the same issue I am experiencing: When editing a post on my phone and saving the changes, I can view the changed post on any machine, but when editing on my laptop I see an outdated version. When then editing on the phone again, the correct (changed) version is shown.

**Comment by thebaer** [comment]
@wiwie Right, since edits are stored locally on your device until you publish, your laptop is loading those local edits instead of the most up-to-date post content. I'm working on fixing this now.

**Comment by wiwie** [comment]
ok, cool!

I recently read somewhere, that write.as stores some things locally in the browser session to facilitate a higher level of data security. Is the aspect of editing a draft not connected to that?

**Comment by thebaer** [comment]
Draft editing is connected that -- changes to posts are stored in the browser, which is why things can get out of sync across devices.
