### ISSUE TITLE
Backend .css setting error

### ISSUE THREAD

**Issue by ghost** [writeas/writefreely#410]
Customizing blog posts in the *Writefreely* .css editor allows to demonstrate that:

- [ ]  `<h1>` titles of a blog post are effectively declared/processed as bigger `<h2>` elements;
- [ ]  `<h2>` elements seem to be `<span>` vs. `<div>`, hence preventing a border-bottom property to be pictured on the page width.

**Comment by 5cr1pt3xt** [comment]
Could be related to the `<h2>` statement here:  `writefreely/templates/include/posts.tmpl`

**Comment by thebaer** [comment]
Hi, could you be a bit more specific about any particular bug you've found?

**Comment by 5cr1pt3xt** [comment]
Hi. Customising the <h2> style in the .css window also impacts <h1> elements in posts and pages.

**Comment by thebaer** [comment]
Could you share the specific CSS you're using, plus a screenshot or URL to the blog? Just trying to figure out if this is a bug in the software or not.

**Comment by thebaer** [comment]
Closing this since we don't have a clear idea of any particular bug here.
