### ISSUE TITLE
Anchor links render proper in Drafts, but not when Published

### ISSUE THREAD

**Issue by mrvdb** [writeas/writefreely#42]
Example draft:

  https://qua.name/2m130piy6f

Example post:
  
  https://qua.name/debug/test-for-anchors

Sources are the same

(UPDATE: patch installed on qua.name, so those links don't show the problem anymore)

**Comment by thebaer** [comment]
Yep, this is another hashtag parsing issue. Similar to #6, we shouldn't be replacing "hashtags" inside `href` attributes or the URL part of a Markdown link. It's manifesting this way (working on drafts) because hashtag parsing doesn't run on drafts.

**Comment by mrvdb** [comment]
The situation could be improved with a reasonable change until we come up with something more structural:

1. require hashtags to have spaces around them, thus change the regex to `' #([\p{L}\p{M}\d]+) '` (and adjust replacement code obviously)
2. do hashtag replacement in drafts to so the rendering is the same.

The effect of the first is that the normal hashtags will keep working as intended, the anchors will start working and less code hashtags will be matched. The user has than a bit more control as well.

I've tested the first and that seems to be a reasonable compromise so far for my needs. I haven't checked enabling hashtag replacment for drafts, but the difference caused by this particular issue for anchors is gone anyway

Thoughts?

**Comment by thebaer** [comment]
Added some thoughts on this fix in #43. I'd really like to get a long-term fix in that can address all of these issues, because the current hashtag parsing via regex is really the least-worst option.

**Comment by mrvdb** [comment]
No problem, I'm maintaining local patches anyway for qua.name.  I needed a bit more controle than there is now.

**Comment by thebaer** [comment]
Fixed in #43
