### ISSUE TITLE
Special characters throw Invalid JSON for POST

### ISSUE THREAD

**Issue by robertabramski** [writeas/writefreely#46]
### Describe the bug
When sending text with special characters, such as an ellipsis `…` or curly quotes `‘`, the API request returns an error. The JSON being sent validates with a [linter](https://jsonlint.com/), but not is not valid here. Typing these characters in the editor works as expected.

### Steps to reproduce (if necessary)
1. Send a `POST` to `/api/posts` or `api/collections/{COLLECTION_ALIAS}/posts` with a JSON object using a special character from above.

### Expected behavior
The JSON payload should be accepted as valid and a new entry should be made.

### Application configuration
 - Multi-user mode
 - Open registration yes
 - Federation enabled yes

**Version or last commit**:
writefreely v0.4.0

**Comment by thebaer** [comment]
Thanks. What's the exact API response coming back? And the JSON payload you're sending? That'll help me see if I can replicate this.

**Comment by robertabramski** [comment]
Certainly. The JSON error response I'm getting back is as follows.

```
{ code: 400, error_msg: 'Expected valid JSON object.' }
```

Here is the JSON object that the API request is getting hung up on because of the single right quote `’` characters.

```
{
	"source": {
		"type": "twitter",
		"id": "165173047387623425",
		"text": "Romney: \"I’m not concerned about the very poor. We have a safety net there. If it needs a repair , I’ll fix it.\" That sound Presidential?",
		"createdAt": "2012-02-02T20:41:37.000Z"
	},
	"text": "Romney: \"I’m not concerned about the very poor. We have a safety net there. If it needs a repair , I’ll fix it.\" That sound Presidential?",
	"sfw": true,
	"tags": [],
	"_id": "19xtf1vl",
	"sortId": 65,
	"published": false
}
```

This one also throws the same error because of the ellipsis `…` character.

```
{
	"source": {
		"type": "twitter",
		"id": "725195252638834688",
		"text": "Try to keep an open mind with this next statement, but…",
		"createdAt": "2016-04-27T05:29:56.000Z"
	},
	"text": "Try to keep an open mind with this next statement, but…",
	"sfw": true,
	"tags": [],
	"_id": "19xtf221",
	"sortId": 297,
	"published": false
}
```

Let me know if you need anything else.

**Comment by thebaer** [comment]
Ah, be sure you're only submitting the arguments listed [in the docs](https://developers.write.as/docs/api/#publish-a-post). The property names in these JSON objects are incorrect, which is why you're seeing that error. For example, `"text"` should actually be `"body"`.

Fixing your JSON object should make this work. Let us know [on the forums](https://discuss.write.as/c/development/platform) if you need more help with the API.

**Comment by robertabramski** [comment]
Apologies. You are correct. This JSON payload is being translated to the
API with an import script I wrote. If you take the string from the text
property and POST as the body, you should see the error.

**Comment by thebaer** [comment]
Mm I'm not seeing the same thing. Both of these payloads work on v0.5 and v0.6 (and should work just the same on v0.4, as there haven't been any changes with data parsing):

```json
{"body": "Romney: \"I’m not concerned about the very poor. We have a safety net there. If it needs a repair , I’ll fix it.\" That sound Presidential?"}
```
or this:
```json
{"body": "Try to keep an open mind with this next statement, but…"}
```
