### ISSUE TITLE
Can't change drafts' created date

### ISSUE THREAD

**Issue by misaka00251** [writeas/writefreely#50]
### Describe the bug
When change a draft post's date, it shows "404 page not found".
But that date is actually changed.

### Steps to reproduce (if necessary)
1. Login
2. Post some stuff and save to drafts.
3. Edit that post's date.

### Expected behavior
"Changes saved"?

### Application configuration
 - Single user mode

**Version or last commit**:
0.6.0

**Comment by thebaer** [comment]
Thanks for reporting this! Will get it fixed in the next release.
