### ISSUE TITLE
Docker build doesn't compile static assets

### ISSUE THREAD

**Issue by thebaer** [writeas/writefreely#57]
### Describe the bug
v0.7 added a build dependency on go-bindata for including database schema files in the final binary. But when building the Docker image, the static data file isn't generated at the correct time, and the build fails. 

I could use help on this from anyone with more Docker experience, cc @koehn @BenOvermyer @kaiyou @jlelse

### Steps to reproduce (if necessary)
1. Run `make build-docker`
1. Wait a while
1. Get `app.go:276:18: undefined: Asset` _(normally defined in the generated `bindata.go` file)_

### Expected behavior
Image successfully builds

### Application configuration
N/A

**Version or last commit**: v0.7.0

**Comment by geekgonecrazy** [comment]
Shouldn’t make deps actually be first before any of the other steps?  If I get a chance I’ll try tomorrow.

**Comment by thebaer** [comment]
No worries, thanks @BenOvermyer!

**Comment by kaiyou** [comment]
I just pushed what I believe is a fix and opened a PR. If anyone can test with me, we can probably merge this quickly.

**Comment by matthiasbeyer** [comment]
I get 

```
./app.go:613:17: undefined: Asset
```

When trying out v0.9.1 and the same error (but another line) with v0.10.0

Is this related or shall I open a new issue for it?

**Comment by thebaer** [comment]
Hey @matthiasbeyer, are you using the official Docker image? Or building it yourself with `make build-docker`?

If it's the former, then that's a separate issue -- we just need to fix the build that's out there. If it's the latter, then yes this is the same error, and we should reopen this issue.

**Comment by matthiasbeyer** [comment]
Neither, I'm trying to package it for nixos and am seeing this error in the process.

**Comment by thebaer** [comment]
Gotcha. Just run `make assets` and that'll fix it.

(On that note, if you want to help us build our documentation for package maintainers, please feel free to open an issue [here](https://github.com/writefreely/documentation). It'd be helpful to know what steps you were going through when trying to build, and what information we're missing in the docs.)
