### ISSUE TITLE
User creation timestamp set to zeros somewhere after Dec. 14, 2018

### ISSUE THREAD

**Issue by mrvdb** [writeas/writefreely#60]
After upgrading to latest git (0.7-ish) looking at the user list in the admin settings. The `created` field of users registered after Dec. 14 or so has the creation timestamp set to '0000-00-00 00:00::00'.

I can't see anything wrong with our particular instance (qua.name) so registering this here to see if others see it too.

db:mysql (mariadb)
multiuser/registration open

**Comment by mrvdb** [comment]
A git bisect points me to this revision as the first bad:

https://github.com/writeas/writefreely/commit/6cb86214d7a50d1125fde892cd9fc7c78075eae9#diff-320bbef96d874515320f176727a55ea8

**Comment by thebaer** [comment]
Yeah, I was worried about that change. Fixing that now.

**Comment by mrvdb** [comment]
Turned out to be a local issue, upgrade of the `created` column(s) in the mentioned revision was not applied by me apparently.

**Comment by thebaer** [comment]
Yeah, plus I didn't actually include that information with the release notes, which I should've done. I'm working on an automated migration mechanism for the next release, so this problem should go away soon. But if I can't get that in for some reason, yes, an UPGRADE file would be a good idea.
