### ISSUE TITLE
Broken build on 0.7.0

### ISSUE THREAD

**Issue by SamWhited** [writeas/writefreely#62]
Similar to #17, the build appears to be broken again when using modules.

Right now the error is:

```
go: github.com/writeas/activity@v0.1.1: parsing go.mod: unexpected module path "github.com/go-fed/activity"
```
In the tag for github.com/writeas/activity@v0.1.1 it is still named `github.com/go-fed/activity` in the mod file; the problem is already fixed, but no new release of `github.com/writeas/activity` has ever been made that writefreely can use.

**Comment by thebaer** [comment]
Ah, thanks for the reminder. Just tagged `github.com/writeas/activity` with a new version -- let me know if there's anything else that needs to be done
