### ISSUE TITLE
Field 'description' doesn't have default value

### ISSUE THREAD

**Issue by MasterGroosha** [writeas/writefreely#7]
```
ERROR: 2018/11/11 11:57:33 log.go:26: Rolling back collections INSERT: Error 1364: Field 'description' doesn't have a default value
ERROR: 2018/11/11 11:57:33 log.go:26: Unable to create user: Error 1364: Field 'description' doesn't have a default value
```

I had to manually change 
`description` varchar(160) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL
to
`description` varchar(160) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT ''

however after that it shows the same problem with `privacy` field. Either something wrong with my mySQL or with your schema.sql.
`Server version: 5.7.18-0ubuntu0.16.10.1 (Ubuntu)`

**Comment by kaniini** [comment]
This seems to be a problem with MariaDB.

**Comment by MasterGroosha** [comment]
@kaniini I had MariaDB beforehand, but I removed MariaDB and clean installed Mysql-Server-5.7 before installing WriteFreely. I hope no tails of MariaDB left behind.

**Comment by thebaer** [comment]
Could you pull in the latest changes on `master` to see if that fixes it?

**Comment by kaniini** [comment]
That fixed it, thanks for the quick fix.

**Comment by MasterGroosha** [comment]
I'm afraid this issue isn't fixed in 0.2 :(

`ERROR: 2018/11/13 00:40:27 log.go:26: Couldn't insert into posts: Error 1364: Field 'privacy' doesn't have a default value`
While trying to post.

**Comment by thebaer** [comment]
Hmm, yeah not sure what's up with it, but again I'm fixing it in the application.

**Comment by Fastidious** [comment]
@thebaer OK, so this error is a show stopper, as I can't post. Waiting for `0.2.1` now. :-)

**Comment by thebaer** [comment]
Okay, [v0.2.1 is out now](https://github.com/writeas/writefreely/releases/tag/v0.2.1) -- let me know if that fixes things!

**Comment by MasterGroosha** [comment]
@thebaer works like a charm now, thank you! 
I'm seeing "scheduled" mark near every published message, is that okay?

**Comment by thebaer** [comment]
Great! 

Is your database on a different timezone? Or is the date set correctly on your machine?

**Comment by MasterGroosha** [comment]
@thebaer Both server and my PC are set to UTC+3 (Moscow time)

**Comment by thebaer** [comment]
So are you running both the app and MySQL on the same machine? And to be sure, when your PC and MySQL are both on the same timezone, does publishing _new_ posts still show them as Scheduled?

**Comment by MasterGroosha** [comment]
I'm running WriteFreely and MySQL on the same dedicated server which has UTC+3 as its timezone. My PC from which I'm making posts is also on UTC+3.

I even performed a clean install of WriteFreely. Downloaded source code, edited `schema.sql` by adding `DROP TABLE IF EXISTS {table_name}` before any `CREATE TABLE` commands.

After going through initial setup, I open my instance and make post. It shows as "Scheduled", though it is visible for everyone. You can check it yourself by visiting https://duck.cf/ 

I even tried re-creating instance once more and added `SET time_zone = '+03:00'` in `schema.sql`, with no luck

**Comment by thebaer** [comment]
Oh yeah, I see. Can you open a new issue about this? Definitely seems like a bug we need to fix.
