### ISSUE TITLE
Admin account isn't created correctly with --config

### ISSUE THREAD

**Issue by aveao** [writeas/writefreely#71]
### Describe the bug
When you just run `./writefreely --config` and supply admin username and password, admin account isn't created correctly.

![SQLite3 showing that there's no registered users](https://elixi.re/i/53u4lrxb.png)

!["User doesn't exist" on writefreely login](https://elixi.re/i/8ihif03t.png)

[Output during --config](https://gist.github.com/aveao/dd3df063e15a827fda928df911aa3c8b)

### Steps to reproduce (if necessary)
1. Download and extract writefreely 0.8.0 somewhere (tried on both /opt, used sudo all the way through, and on my home folder with no sudo)
2. Run `writefreely --config`
3. Do a setup that is similar to the log provided above or to the application configuration provided below, provide admin credentials.
4. Run `sqlite3 writefreely.db`, run `select * from users;`
5. Observe that there's no users.

### Expected behavior
An admin user should've been created.

### Application configuration
 - **Single mode or Multi-user mode?** Single mode
 - **Database?** SQLite
 - **Open registration?** no
 - **Federation enabled?** yes

**Version or last commit**:
0.8.0 for Linux, directly from [releases](https://github.com/writeas/writefreely/releases/tag/v0.8.0), running on a Ubuntu 16.04 xenial server.

---

As a sidenote:

1) I pasted my password on the box there and it was a 64 character a-zA-Z0-9 password, but it appeared there and writefreely gave it a checkmark (:heavy_check_mark:).
2) Doing `./writefreely --create-admin username:password` with the same credentials did create the account, and now I can use writefreely.

**Comment by thebaer** [comment]
Thanks for reporting this! Looks like the `adminInitDatabase()` func was causing the app to exit early during the config process. I'll push a fix soon, and we'll do a bugfix release that includes the patch early this week.

**Comment by aveao** [comment]
Thanks for fixing this so quickly!
