### ISSUE TITLE
Couldn't saveUserSession: securecookie: hash key is not set

### ISSUE THREAD

**Issue by laoshaw** [writeas/writefreely#75]
./writefreely -config

choose sqlite3, set admin/admin as username

sudo ./writefreely

google-chrome http://localhost:80

can not post anything, log showed "Login: Couldn't save session: securecookie: hash key is not set"

tried development mode and production mode, no help

running the newest release on ubuntu 18.04 64bit

**Comment by thebaer** [comment]
This will happen if you don't run the key generation step outlined in the [install guide](https://writefreely.org/start):

```
writefreely --gen-keys
```

Did that fix it for you?

**Comment by laoshaw** [comment]
yes. thanks.
