### ISSUE TITLE
Scheduled posts available via federation

### ISSUE THREAD

**Issue by carbontwelve** [writeas/writefreely#76]
### Describe the bug

I just noticed on 0.8.1 that when I schedule posts with dates in the future that they become available via federation immediately.

### Steps to reproduce (if necessary)
1. Create a new draft post and give it a `created` date in the future
2. Move post from drafts to a public blog
3. Note that viewing the blog while logged in shows it as being Scheduled 
4. Note that viewing the blog while logged out doesn't show the post
5. Using Pleroma/Mastodon lookup the blogs federated address
6. Notice the scheduled post appears in the post listing from Pleroma/Mastodon with its created date showing correctly

### Expected behavior

I would expect that a post with status scheduled would not be published via federation until after its `created` date. If it's not visible from the blogs url when logged out it shouldn't be visible via federation.

### Application configuration

- https://wordsmith.social/carbontwelve
 - Multi-user mode
 - **Database** mysql
 - **Open registration?** yes
 - **Federation enabled?** yes

**Version or last commit**: 0.8.1

**Comment by thebaer** [comment]
Thanks for the report, I was able to replicate this as well. Looking into the cause now -- probably some missing logic.

Beyond just not publishing to the fediverse in this case, to get the full scheduling functionality, we'll also need to add some kind of mechanism that regularly checks for scheduled posts and federates them out. That'll be part of a larger undertaking we're tracking here: https://writefreely.org/tasks/567

**Comment by carbontwelve** [comment]
@thebaer nice one.

**Comment by HDValentin** [comment]
If I plan a writefreely post, to publish it in the future it gets not published into the Fediverse, e.g. Mastodon. 

The same happens, if I mention a Fediverse profile in the post. 
If I edit and save the post after it was published, the profile gets the notification.

Is here the right place for this issue or should I open a new one for it?

**Comment by thebaer** [comment]
@HDValentin sounds like a new, separate issue -- please open a new one for it!

**Comment by HDValentin** [comment]
@thebaer Done
https://github.com/writefreely/writefreely/issues/821

@escuco
