### ISSUE TITLE
2nd (##) and 1st (#) level headings show as same style on blog feed

### ISSUE THREAD

**Issue by christianpetty** [writeas/writefreely#82]
Hi,

It appears that first and second (maybe more) level headings show as the same size and style when viewing the post from the blog’s index. Clicking on the post then corrects it to the right style. 

Was this intentional?

**Comment by thebaer** [comment]
Hey, good catch. This isn't intentional; it's is one of a few design bugs / differences between posts on the blog index and individual post pages that we need to fix. Just need to dig into the CSS that's grown unwieldy over time. Thanks for the report!
