### ISSUE TITLE
WriteFreely runs as root

### ISSUE THREAD

**Issue by gytisrepecka** [writeas/writefreely#85]
Based on system service configuration file provided in [production documentation](https://writefreely.org/start#production), **writefreely** binary will run under **root** system user. To fix this, make sure to add following parameters in **Service** section:
`User=writefreely`
`Group=writefreely`
After systemctl daemon is reloaded, you will see writefreely binary now runs under corresponding user:
`ps aux | grep writefreely`

**Comment by gytisrepecka** [comment]
Full configuration file here: https://gist.github.com/gytisrepecka/557660aed94afebec68c0a2432ae348e

**Comment by thebaer** [comment]
For this, we'll also need to update the documentation to include the creation of the `writefreely` user, right? Would you mind creating an issue for this in the [documentation repo](https://github.com/writefreely/documentation)?

**Comment by gytisrepecka** [comment]
Yes, I can document that.

**Comment by thebaer** [comment]
Going to close this out since it isn't a bug. Let's continue discussing this on the documentation repo.

**Comment by cburkert** [comment]
Its 2023 and the installation guide still leads users to an instance running fully as root.
I couldn't find any continuation of this discussion on the documentation repo.
Could anyone please give me a pointer or did the discussion end here?
