### ISSUE TITLE
Cannot login (session not saved)

### ISSUE THREAD

**Issue by emorozov** [writeas/writefreely#87]
### Describe the bug
I've set up private writefreely instance on my VPS as described on the QuickStart page.
The only difference is that I've used a different user to run the writefreely service in systemd as opposed to the QuickStart documentation that runs server as `root`.

I cannot log in to my instance (got redirected to log in form on every attempt) and I see the following error message in the logs:
```
Apr 03 17:24:52 hostname writefreely[17486]: ERROR: 2019/04/03 17:24:52 log.go:26: Login: Couldn't save session: securecookie: hash key is not set
```

All files belong to the user that runs the writefreely user, so there can't be any permission issues, unless it tries to write outside of the home directory for the user.

 - **Single mode** 
 - **Database?** sqlite
 - **Open registration?** no
 - **Federation enabled?** yes

**Version or last commit**:
0.8.1

**Comment by thebaer** [comment]
Did you run the `writefreely --gen-keys` step?

**Comment by emorozov** [comment]
Sorry, my bad. Shouldn't set up a new software late night. Works perfectly now.

**Comment by thebaer** [comment]
No problem :+1:
