### ISSUE TITLE
While post is in draft, meta tags are referring to write.as

### ISSUE THREAD

**Issue by gytisrepecka** [writeas/writefreely#91]
### Describe the bug
While post is saved as draft several meta tag values uses write.as while instance domain is expected. When post is published, meta tags are ok.

While post is saved as draft following meta tags are incorrect:
`<meta name="twitter:image" content="https://write.as/img/w-sq-light.png">`
`<meta property="og:url" content="https://write.as/xmta31a2yl" />`
`<meta property="og:image" content="https://write.as/img/w-sq-light.png">`

### Expected behavior
Expected is to see instance's domain:
`<meta name="twitter:image" content="https://fedi.dev/img/avatars/g.png">`
`<meta property="og:url" content="https://fedi.dev/xmta31a2yl" />`
`<meta property="og:image" content="https://fedi.dev/img/avatars/g.png">`

**Version or last commit**: v0.8.1-18-g372b4e5

**Comment by thebaer** [comment]
Good catch, thanks!
