### ISSUE TITLE
Build fails on sitemap.go

### ISSUE THREAD

**Issue by gytisrepecka** [writeas/writefreely#93]
### Describe the bug
Building WriteFreely from source (version 0.9) fails with following error:

```
go-bindata -pkg writefreely -ignore=\\.gitignore schema.sql sqlite.sql
go get -tags='sqlite' -d -v ./...
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
	ignoring go.mod;
	see 'go help modules'
github.com/mattn/go-sqlite3 (download)
cd cmd/writefreely; go build -ldflags="-X 'github.com/writeas/writefreely.softwareVer=`git describe --tags | cut -c 2-`'" -v -tags='sqlite'
github.com/mattn/go-sqlite3
github.com/writeas/writefreely/parse
github.com/writeas/writefreely
# github.com/writeas/writefreely
../../sitemap.go:23:22: not enough arguments in call to stm.NewSitemap
	have ()
	want (int)
../../sitemap.go:78:4: index must be non-negative integer constant
../../sitemap.go:78:4: cannot use p.Post.Slug.NullString.String (type string) as type []interface {} in array or slice literal
../../sitemap.go:79:4: index must be non-negative integer constant
../../sitemap.go:79:18: cannot use "weekly" (type string) as type []interface {} in array or slice literal
../../sitemap.go:80:4: index must be non-negative integer constant
../../sitemap.go:80:4: cannot use true (type bool) as type []interface {} in array or slice literal
../../sitemap.go:81:4: index must be non-negative integer constant
../../sitemap.go:81:4: cannot use p.Post.Updated (type time.Time) as type []interface {} in array or slice literal
../../sitemap.go:86:33: index must be non-negative integer constant
../../sitemap.go:86:33: too many errors
make: *** [build] Error 2
```

### Steps to reproduce (if necessary)
1. go get -d -u github.com/writeas/writefreely/cmd/writefreely
2. cd go/src/src/github.com/writeas/writefreely
3. make build

Building on CentOS 7.

### Expected behavior
Build succeeded and writefreely available in go/bin.

**Version or last commit**:
0.9

**Comment by yalh76** [comment]
Same error trying to build for linux/arm64 and linux/amd64

**Comment by thebaer** [comment]
Can you try building with Go Modules enabled and see if you still get this error?

**Comment by yalh76** [comment]
> 
> 
> Can you try building with Go Modules enabled and see if you still get this error?

Do you have the command line for that ?

**Comment by diazepan** [comment]
It's by adding GO111MODULE=on

What I do is the following:
1) go get -d github.com/writeas/writefreely/cmd/writefreely
2) GO111MODULE=on go build github.com/writeas/writefreely/cmd/writefreely
3) wait until it has errors
4) Making the assets and the ui
5) Running again GO111MODULE=on go build github.com/writeas/writefreely/cmd/writefreely

And that worked for me

**Comment by gytisrepecka** [comment]
In my case prepending all make commands with **GO111MODULE=on** helped, e.g.:
```
GO111MODULE=on make build
```
Thanks, I will make a detailed build documentation as there are few little details (at least on CentOS) :)

**Comment by thebaer** [comment]
@gytisrepecka That would be great! I'll create a "developer" section in the documentation repo that you can add to.

**Comment by yalh76** [comment]
> 
> 
> In my case prepending all make commands with **GO111MODULE=on** helped, e.g.:
> 
> ```
> GO111MODULE=on make build
> ```
> 
> Thanks, I will make a detailed build documentation as there are few little details (at least on CentOS) :)

For me too, build for ARM64 working

**Comment by gytisrepecka** [comment]
I have drafted [full building walkthrough](https://fedi.dev/gytis/build-writefreely-from-source) with mentioned fix, would be nice if someone would also try out on CentOS/RHEL :)

**Comment by kaiyou** [comment]
Just pushed the related fixes for the Docker build, thank you for the walkthrough :)

**Comment by joicemjoseph** [comment]
> GO111MODULE=on make build
After trying this, I am getting 
`Makefile:60: recipe for target 'deps' failed` error.

on ubuntu 18.04

**Comment by gytisrepecka** [comment]
Did you use `go get` to update sources and dependencies from Git?
